{
 "title": "Cluster Pod & Node Issues",
 "description": "Shows Pods & Nodes that have a bad state",
 "tags": [
  "Nodes",
  "Pods"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\"}, namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_status_condition{condition=\"Ready\",status=\"true\"},node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_swap{namespace=~\"$namespace\",job=~\"kubernetes-.*\", image!=\"\", instance=~\"$node\",pod!~\".*-deploy\"}, pod)"
    }
   },
   {
    "name": "terminated_reasons",
    "label": "Container Terminated Reasons",
    "query": "ContainerCannotRun,DeadlineExceeded,Error,OOMKilled"
   },
   {
    "name": "waiting_reasons",
    "label": "Container Waiting Reasons",
    "query": "CrashLoopBackOff,CreateContainerConfigError,CreateContainerError,ErrImagePull,ImagePullBackOff,InvalidImageName"
   },
   {
    "name": "node_conditions",
    "label": "Node Conditions",
    "query": {
     "query": "label_values(kube_node_status_condition{condition!=\"Ready\"},condition)"
    }
   },
   {
    "name": "pod_reasons",
    "label": "Pod Status Reasons",
    "query": {
     "query": "label_values(kube_pod_status_reason,reason)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "including master nodes",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Unschedulable Nodes",
   "type": "stat",
   "description": "Number of App Nodes which are unschedulable",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Bad Event Nodes",
   "type": "stat",
   "description": "Number of Nodes which had a bad condition event at the Node side.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=~\"$node_conditions\",status=\"true\"}) + sum(kube_node_status_condition{node=~\"$node\",condition=\"Ready\",status=\"true\"} == bool 0)"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "description": "Number of running containers in the namepsace",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=~\"$namespace\"}>0)"
    }
   ]
  },
  {
   "title": "Not Ready Containers",
   "type": "stat",
   "description": "Running Containers - Ready Containers",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=~\"$namespace\"}) - count(kube_pod_container_status_ready{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Restarting Containers",
   "type": "stat",
   "description": "Number of container which are restarting more than 5 times/hour",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[1h]) > 5) or vector(0)"
    }
   ]
  },
  { "title": "Bad Node Event Conditions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "NotReady",
   "type": "stat",
   "description": "#Events of Node in bad shape due to Not Ready over the period",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{node=~\"$node\",condition=\"Ready\",status=\"true\"} == bool 0)"
    }
   ]
  },
  {
   "title": "$node_conditions",
   "type": "stat",
   "description": "#Events of Node in bad shape due to $node_conditions over the period",
   "gridPos": { "h": 2, "w": 12, "x": 4, "y": 4 },
   "repeat": "node_conditions",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"$node\",condition=~\"$node_conditions\",status=\"true\"}>0) or vector(0)"
    }
   ]
  },
  { "title": "Bad Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$pod_reasons",
   "type": "stat",
   "description": "#Events of Pods due to $pod_reasons over the period",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "repeat": "pod_reasons",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{namespace=~\"$namespace\",pod=~\"$pod\",reason=~\"$pod_reasons\"}) > 0 or vector(0)"
    }
   ]
  },
  {
   "title": "Container Terminated Event Reasons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "$terminated_reasons",
   "type": "stat",
   "description": "#Events of Terminated containers due to $terminated_reasons over the period",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "repeat": "terminated_reasons",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\",pod=~\"$pod\",reason=~\"$terminated_reasons\"}) > 0 or vector(0)"
    }
   ]
  },
  {
   "title": "Container Waiting Event Reasons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "$waiting_reasons",
   "type": "stat",
   "description": "#Events of Waiting containers due to $waiting_reasons over the period",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "repeat": "waiting_reasons",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\",pod=~\"$pod\",reason=~\"$waiting_reasons\"})"
    }
   ]
  },
  { "title": "Node Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bad Node Conditions",
   "type": "timeseries",
   "description": "Nodes on which there may be an issue",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (condition,node)(kube_node_status_condition{node=~\"$node\",condition=~\"$node_conditions\",status=\"true\"}>0)",
     "legendFormat": "{{node}} | {{condition}}"
    },
    {
     "expr": "sum by (condition,node)(kube_node_status_condition{node=~\"$node\",condition=\"Ready\",status=\"true\"} == bool 0) > 0",
     "legendFormat": "{{node}} | NotReady"
    }
   ]
  },
  {
   "title": "Unschedulable Nodes",
   "type": "timeseries",
   "description": "Stacked view from Nodes on which we can not schedule any pods",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kube_node_spec_unschedulable>0", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "timeseries",
   "description": "Last time nodes were restarted",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "(time()-kube_node_created{node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Pod Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Bad Pod Status",
   "type": "timeseries",
   "description": "Number of times a pod was in a bad state. \nIn case of\n- Evicted : a Pod assigned to a Node was asked for termination\n- NodeAffinity : issue with Pod restricted to run on particular Node\n- NodeLost : issue with Pod while running on a Node which was lost\n- Shutdown : issue with Pod while shutdown \n- UnexpectedAdmissionError : Pod unexpected error while attempting to recover from admission failure",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod,reason)(kube_pod_status_reason{namespace=~\"$namespace\",pod=~\"$pod\",reason=~\"$pod_reasons\"}) > 0",
     "legendFormat": "{{pod}} | {{reason}}"
    }
   ]
  },
  { "title": "Container Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Restarting Containers per Hour",
   "type": "timeseries",
   "description": "Number of times a container was restarted per hour (with filtering only the ones that restarted at least 5 times in an hour which is abnormal)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1h]) > 5",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "Terminated Containers",
   "type": "timeseries",
   "description": "Number of times a container was in Terminated state. \nIn case of\n- OOMKilled : click on the graph serie and drill down to Pods dash. \n- Error : check that the pod is in not ready state, it means the readiness probe failed. \n- Evicted : click on the graph serie and drill down to Node Resource VS Limits dash. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod,container,reason)(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\",pod=~\"$pod\",reason=~\"$terminated_reasons\"}) > 0",
     "legendFormat": "{{pod}} | {{container}} | {{reason}}"
    }
   ]
  },
  {
   "title": "Waiting Containers",
   "type": "timeseries",
   "description": "Number of times a container was in Waiting state. \nIn case of\n- CrashLoopBackOff : The application inside the container keeps crashing or some type of parameters of the pod or container have been configured incorrectly \n- CreateContainerConfigError : most of the time due to a volume mounting issue. \n- CreateContainerError : check an issue with the OCP control plane. \n- ErrImagePull/ImagePullBackOff/InvalidImageName : issue with the docker Image to be pulled ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod,container,reason)(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\",pod=~\"$pod\",reason=~\"$waiting_reasons\"}) > 0",
     "legendFormat": "{{pod}} | {{container}} | {{reason}}"
    }
   ]
  },
  {
   "title": "Not Ready Containers",
   "type": "timeseries",
   "description": "Number of times a container was not in Ready state. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(pod,container)(kube_pod_container_status_ready{namespace=~\"$namespace\",pod=~\"$pod\"}<1)",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  }
 ]
}