{
 "title": "AWS Mongo DB Atlas",
 "description": "Visualize Amazon MongoDB Atlas metrics",
 "tags": [
  "AWS",
  "infra"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(adot_mongodb_up,cl_name)"
    }
   },
   {
    "name": "pod",
    "label": "Shard",
    "query": {
     "query": "label_values(adot_mongodb_up{cl_name=\"$cluster\"},instance)"
    }
   },
   {
    "name": "app",
    "label": "Replica Set",
    "query": {
     "query": "label_values(adot_mongodb_up{cl_name=\"$cluster\"},rs_nm)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "If it is UP it means that all MongoDB instances are UP",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "min(adot_mongodb_up{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Shows the storage engine used on the instance (inMemory or wiredTiger)",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by(mongodb_version)(adot_mongodb_info{cl_name=~\"$cluster\"})",
     "legendFormat": "{{mongodb_version}}"
    }
   ]
  },
  {
   "title": "Storage Engine",
   "type": "stat",
   "description": "Shows the storage engine used on the instance (inMemory or wiredTiger)",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(adot_mongodb_storageEngine_persistent{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "#ReplSet",
   "type": "stat",
   "description": "Shows the number of members in the replica set",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (rs_nm) (adot_mongodb_members_state{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Max Query Per Second (opcounters != commands)",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(adot_mongodb_opcountersRepl_delete{cl_name=~\"$cluster\"}[$interval]))+sum(rate(adot_mongodb_opcountersRepl_getmore{cl_name=~\"$cluster\"}[$interval]))+sum(rate(adot_mongodb_opcountersRepl_insert{cl_name=~\"$cluster\"}[$interval]))+sum(rate(adot_mongodb_opcountersRepl_query{cl_name=~\"$cluster\"}[$interval]))+sum(rate(adot_mongodb_opcountersRepl_update{cl_name=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "stat",
   "description": "Any number of queued operations for long periods of time is an indication of possible issues. Find the cause and fix it before requests get stuck in the queue.",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(adot_mongodb_globalLock_currentQueue_total{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Op Latency R",
   "type": "stat",
   "description": "Avg latency for read operations",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(adot_mongodb_opLatencies_reads_latency{cl_name=~\"$cluster\"}[$interval])/rate(adot_mongodb_opLatencies_reads_ops{cl_name=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Op Latency W",
   "type": "stat",
   "description": "Avg latency for writes operations",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(adot_mongodb_opLatencies_writes_latency{cl_name=~\"$cluster\"}[$interval])/rate(adot_mongodb_opLatencies_writes_ops{cl_name=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Query Efficency",
   "type": "stat",
   "description": "AVG Query Efficency",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(adot_mongodb_metrics_document_returned{cl_name=~\"$cluster\"}[$interval]))/sum(rate(adot_mongodb_metrics_queryExecutor_scannedObjects{cl_name=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "days since startup",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(adot_mongodb_uptime{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "#vCPUs",
   "type": "stat",
   "description": "Sum all vCPUs for given instances",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "description": "Sum all memory for given instances",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(adot_hardware_system_memory_mem_total_kilobytes{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Sum all disk storage for given instances",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(adot_hardware_disk_metrics_disk_space_used_bytes{cl_name=~\"$cluster\"})+sum(adot_hardware_disk_metrics_disk_space_free_bytes{cl_name=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\"})-sum(rate(adot_hardware_system_cpu_idle_milliseconds_total{cl_name=~\"$cluster\"}[$interval])))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(adot_hardware_system_memory_mem_total_kilobytes{cl_name=~\"$cluster\"})-sum(adot_hardware_system_memory_mem_free_kilobytes{cl_name=~\"$cluster\"}))/sum(adot_hardware_system_memory_mem_total_kilobytes{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "stat",
   "description": "Please provision more storage when more than 80% usage",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(adot_hardware_disk_metrics_disk_space_used_bytes{cl_name=~\"$cluster\"}) / (sum(adot_hardware_disk_metrics_disk_space_used_bytes{cl_name=~\"$cluster\"})+sum(adot_hardware_disk_metrics_disk_space_free_bytes{cl_name=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "stat",
   "description": "Swap Usage should me small (<10%) to maximize performance with using RAM instead of Disk",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(adot_hardware_system_memory_swap_total_kilobytes{cl_name=~\"$cluster\"})-sum(adot_hardware_system_memory_swap_free_kilobytes{cl_name=~\"$cluster\"}))/sum(adot_hardware_system_memory_swap_total_kilobytes{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Replica Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ReplSet State",
   "type": "table",
   "description": "In MongoDB, a replica set is a group of MongoDB instances that maintain the same data set, providing redundancy and high availability. The status of a replica set can be determined by examining the state of its members. Here are the different states that a member of a replica set can be in:  \n    STARTUP: The member is starting up and has not yet joined the replica set.  \n    STARTUP2: The member is in the process of joining the replica set.  \n    PRIMARY: The member is the primary node and is currently accepting write operations.  \n    SECONDARY: The member is a secondary node and is replicating data from the primary.    \n    RECOVERING: The member is in the process of recovering data from the primary or another secondary.  \n    FATAL: The member has encountered a fatal error and is no longer part of the replica set.  \n    UNKNOWN: The member's state is unknown, which can happen if the member is not reachable.  \n    ARBITER: The member is an arbiter, which does not hold data but participates in elections to help achieve a majority.  \n    DOWN: The member is down or not reachable.  \n    ROLLBACK: The member is in the process of rolling back to a consistent state.  \n    REMOVED: The member has been removed from the replica set.  \n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (alias_instance,alias_member,rs_state)(label_replace(label_replace(adot_mongodb_members_state{cl_name=~\"$cluster\",instance=~\".*($pod).*\"},\"alias_instance\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"),\"alias_member\",\"$1\",\"member_idx\",\"(.*\\\\d\\\\d-\\\\d\\\\d).*\"))",
     "legendFormat": "Shard {{alias_instance}} | Member {{alias_member}} | Replica Set {{rs_state}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Commands",
     "type": "timeseries",
     "description": "Shows how many times a command is executed per second on average during the selected interval.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opcountersRepl_command{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "cmd {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opcountersRepl_getmore{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "getmore {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opcountersRepl_query{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "query {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opcountersRepl_delete{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "delete {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opcountersRepl_insert{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "insert {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opcountersRepl_update{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "update {{alias}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "Average latency of operations (classified by read, write, or (other) command)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opLatencies_commands_latency{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])/rate(adot_mongodb_opLatencies_commands_ops{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "cmd {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opLatencies_reads_latency{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])/rate(adot_mongodb_opLatencies_reads_ops{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "reads {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opLatencies_writes_latency{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])/rate(adot_mongodb_opLatencies_writes_ops{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "writes {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_opLatencies_transactions_latency{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])/rate(adot_mongodb_opLatencies_transactions_ops{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "transactions {{alias}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Keep in mind the hard limit on the maximum number of connections set by your distribution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(adot_mongodb_connections_active{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(adot_mongodb_connections_awaitingTopologyChanges{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Awaiting"
      },
      {
       "expr": "sum(adot_mongodb_connections_current{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Current"
      },
      {
       "expr": "sum(adot_mongodb_connections_exhaustHello{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "exhaustHello"
      },
      {
       "expr": "sum(adot_mongodb_connections_exhaustIsMaster{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "exhaustIsMaster"
      },
      {
       "expr": "sum(adot_mongodb_connections_limitExempt{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "limitExempt"
      },
      {
       "expr": "sum(adot_mongodb_connections_rejected{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "rejected"
      },
      {
       "expr": "sum(adot_mongodb_connections_threaded{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "threaded"
      }
     ]
    },
    {
     "title": "Cursors",
     "type": "timeseries",
     "description": "Helps identify why connections are increasing. Shows active cursors compared to cursors being automatically killed after 10 minutes due to an application not closing the connection.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(adot_mongodb_metrics_cursor_open_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(adot_mongodb_metrics_cursor_open_pinned{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Pinned"
      },
      {
       "expr": "sum(adot_mongodb_metrics_cursor_open_noTimeout{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "no Timeout"
      }
     ]
    },
    {
     "title": "Document",
     "type": "timeseries",
     "description": "When used in combination with 'Command Operations', this graph can help identify write amplification. For example, when one insert or update command actually inserts or updates hundreds, thousands, or even millions of documents.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_metrics_document_inserted{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Inserted"
      },
      {
       "expr": "sum(rate(adot_mongodb_metrics_document_deleted{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Deleted"
      },
      {
       "expr": "sum(rate(adot_mongodb_metrics_document_updated{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Updated"
      }
     ]
    },
    {
     "title": "Queued",
     "type": "timeseries",
     "description": "Any number of queued operations for long periods of time is an indication of possible issues. Find the cause and fix it before requests get stuck in the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(adot_mongodb_globalLock_currentQueue_readers{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Readers"
      },
      {
       "expr": "sum(adot_mongodb_globalLock_currentQueue_writers{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Writers"
      },
      {
       "expr": "sum(adot_mongodb_globalLock_currentQueue_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Query Efficiency",
     "type": "timeseries",
     "description": "Page faults indicate that requests are processed from disk either because an index is missing or there is not enough memory for the data set. Consider increasing memory or sharding out.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_metrics_document_returned{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/sum(rate(adot_mongodb_metrics_queryExecutor_scannedObjects{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Efficiency"
      }
     ]
    },
    {
     "title": "Scanned Objects",
     "type": "timeseries",
     "description": "The average rate per second over the selected sample period of documents scanned during queries and query-plan evaluation. This rate is driven by the same value as totalDocsExamined in the output of explain().",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_metrics_queryExecutor_scannedObjects{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Scanned"
      }
     ]
    },
    {
     "title": "getLastError Write Time",
     "type": "timeseries",
     "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_metrics_getLastError_wtime_totalMillis{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Last Error"
      }
     ]
    },
    {
     "title": "getLastError Write Operations",
     "type": "timeseries",
     "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_metrics_getLastError_wtimeouts{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Timeouts"
      },
      {
       "expr": "sum(rate(adot_mongodb_metrics_getLastError_wtime_num{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Assert Events",
     "type": "timeseries",
     "description": "Asserts are not important by themselves, but you can correlate spikes with other graphs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_asserts_msg{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Messages"
      },
      {
       "expr": "sum(rate(adot_mongodb_asserts_warning{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "User"
      }
     ]
    },
    {
     "title": "Page Faults",
     "type": "timeseries",
     "description": "Page faults indicate that requests are processed from disk either because an index is missing or there is not enough memory for the data set. Consider increasing memory or sharding out.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_extra_info_page_faults{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Faults"
      },
      {
       "expr": "sum(rate(adot_mongodb_extra_info_page_reclaims{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Reclaimed"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "CPU usage on the server,CPU User = CPU used by the application (user+nice), CPU System = CPU used by the kernel, CPU IOWait= CPU waiting for the IOs, CPU Other = CPU used by the IRQ, Steal, Guest",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})-sum(rate(adot_hardware_system_cpu_idle_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))>0",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(adot_hardware_system_cpu_user_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "User"
      },
      {
       "expr": "sum(rate(adot_hardware_system_cpu_kernel_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "System"
      },
      {
       "expr": "sum(rate(adot_hardware_system_cpu_io_wait_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "IOwait"
      },
      {
       "expr": "sum(rate(adot_hardware_system_cpu_nice_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "Nice"
      },
      {
       "expr": "(sum(rate(adot_hardware_system_cpu_guest_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))+sum(rate(adot_hardware_system_cpu_irq_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))+sum(rate(adot_hardware_system_cpu_soft_irq_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))+sum(rate(adot_hardware_system_cpu_steal_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])))\n/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "timeseries",
     "description": "The number of kilobytes of physical memory in use\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "sum(adot_hardware_system_memory_mem_total_kilobytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(adot_hardware_system_memory_mem_total_kilobytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}) -sum(adot_hardware_system_memory_mem_free_kilobytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU Process Usage",
     "type": "timeseries",
     "description": "The percentage of time the CPU spent servicing this MongoDB process, scaled to a range of 0-100% by dividing by the number of CPU cores.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(adot_hardware_process_cpu_user_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "User"
      },
      {
       "expr": "sum(rate(adot_hardware_process_cpu_kernel_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "Kernel"
      },
      {
       "expr": "sum(rate(adot_hardware_process_cpu_children_user_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "Children User"
      },
      {
       "expr": "sum(rate(adot_hardware_process_cpu_children_kernel_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))/(1000*sum(adot_hardware_platform_num_logical_cpus{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}))",
       "legendFormat": "Kernel User"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "description": "The total amount of swap space in free and used, measured in kilobytes\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "sum(adot_hardware_system_memory_swap_total_kilobytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(adot_hardware_system_memory_swap_total_kilobytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}) -sum(adot_hardware_system_memory_swap_free_kilobytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "description": "Network Throughput Logical (uncompressed)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_network_bytesIn{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "sum(rate(adot_mongodb_network_bytesOut{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Out"
      },
      {
       "expr": "sum(rate(adot_mongodb_network_compression_snappy_compressor_bytesIn{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Snappy Comp In"
      },
      {
       "expr": "sum(rate(adot_mongodb_network_compression_snappy_compressor_bytesOut{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Snappy Comp Out"
      },
      {
       "expr": "sum(rate(adot_mongodb_network_compression_snappy_decompressor_bytesIn{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Snappy Decomp In"
      },
      {
       "expr": "sum(rate(adot_mongodb_network_compression_snappy_decompressor_bytesOut{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Snappy Decomp Out"
      }
     ]
    },
    {
     "title": "Network Physical",
     "type": "timeseries",
     "description": "Network Throughput Physical (compressed)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum(rate(adot_mongodb_network_physicalBytesIn{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "sum(rate(adot_mongodb_network_physicalBytesOut{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Storage Usage",
     "type": "timeseries",
     "description": "Disk used and free (stacked view)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(adot_hardware_disk_metrics_disk_space_used_bytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(adot_hardware_disk_metrics_disk_space_free_bytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Storage Latency",
     "type": "timeseries",
     "description": "Disk Latency",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(adot_hardware_disk_metrics_read_time_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])/rate(adot_hardware_disk_metrics_read_count_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(adot_hardware_disk_metrics_write_time_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval])/rate(adot_hardware_disk_metrics_write_count_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Storage IOPS",
     "type": "timeseries",
     "description": "Disk Latency",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(adot_hardware_disk_metrics_read_count_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(adot_hardware_disk_metrics_write_count_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Disk Queue Depth",
     "type": "timeseries",
     "description": "The average length of queue of requests issued to the disk partition used by MongoDB.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(adot_hardware_disk_metrics_weighted_time_io_milliseconds_total{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]))",
       "legendFormat": "Read"
      }
     ]
    }
   ]
  },
  {
   "title": "Oplog Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Oplog Getmore Time",
     "type": "timeseries",
     "description": "n the context of MongoDB, an OpLog (short for Operation Log) is a special capped collection that stores an ordered history of logical write operations (insert, update, delete) that modify the data stored in the database. The OpLog is a crucial component of MongoDB's replication system, enabling the synchronization of data across replica set members.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_metrics_repl_network_getmores_totalMillis{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Oplog Buffer Capacity",
     "type": "timeseries",
     "description": "n the context of MongoDB, an OpLog (short for Operation Log) is a special capped collection that stores an ordered history of logical write operations (insert, update, delete) that modify the data stored in the database. The OpLog is a crucial component of MongoDB's replication system, enabling the synchronization of data across replica set members.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (alias)(label_replace(adot_mongodb_metrics_repl_buffer_sizeBytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"},\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "Used {{alias}}"
      },
      {
       "expr": "max by (alias)(label_replace(adot_mongodb_metrics_repl_buffer_maxSizeBytes{cl_name=~\"$cluster\",instance=~\".*($pod).*\"},\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "Max {{alias}}"
      }
     ]
    },
    {
     "title": "Oplog Operations",
     "type": "timeseries",
     "description": "n the context of MongoDB, an OpLog (short for Operation Log) is a special capped collection that stores an ordered history of logical write operations (insert, update, delete) that modify the data stored in the database. The OpLog is a crucial component of MongoDB's replication system, enabling the synchronization of data across replica set members.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max by (alias)(label_replace(rate(adot_mongodb_metrics_repl_apply_ops{cl_name=~\"$cluster\",instance=~\".*($pod).*\"}[$interval]),\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Oplog Buffered Operations",
     "type": "timeseries",
     "description": "n the context of MongoDB, an OpLog (short for Operation Log) is a special capped collection that stores an ordered history of logical write operations (insert, update, delete) that modify the data stored in the database. The OpLog is a crucial component of MongoDB's replication system, enabling the synchronization of data across replica set members.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max by (alias)(label_replace(adot_mongodb_metrics_repl_buffer_count{cl_name=~\"$cluster\",instance=~\".*($pod).*\"},\"alias\",\"$1\",\"instance\",\".*(\\\\d\\\\d-\\\\d\\\\d).*\"))",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  }
 ]
}