{
 "title": "Zookeeper",
 "description": "The Zookeeper dashboard provides a detailed view of the Zookeeper service, including the overall status of the cluster and the statistics metrics, such as the latency, packets, ephemerals, approximate data size, alive connections, and so on.",
 "tags": [ "Zookeeper" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", container=~\"zookeeper\"},namespace)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "2m" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_memory_swap{pod=~\".*-zookeeper-.*\", namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_swap{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of zookeeper",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zookeeper_ElectionType{pod=~\"$cluster(-\\\\d+-\\\\d+-\\\\w+|-\\\\d+)\"})/max(zookeeper_QuorumSize{pod=~\"$cluster(-\\\\d+-\\\\d+-\\\\w+|-\\\\d+)\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "description": "Number of zookeeper services",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_OutstandingRequests{pod=~\"$cluster(-\\\\d+-\\\\d+-\\\\w+|-\\\\d+)\"})"
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "stat",
   "description": "Number of zookeeper services in quorum",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zookeeper_QuorumSize{pod=~\"$cluster(-\\\\d+-\\\\d+-\\\\w+|-\\\\d+)\"})"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "stat",
   "description": "Number of followers within the ensemble (should be quorum -1 ,ie 1 leader)",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_MaxClientCnxnsPerHost{pod=~\"$cluster(-\\\\d+-\\\\d+-\\\\w+|-\\\\d+)\",memberType=\"Follower\"})"
    }
   ]
  },
  {
   "title": "Synched Followers",
   "type": "stat",
   "description": "Number of followers which are in synched",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_PendingRevalidationCount{pod=~\"$cluster(-\\\\d+-\\\\d+-\\\\w+|-\\\\d+)\"} == 0)"
    }
   ]
  },
  {
   "title": "Pending Syncs",
   "type": "stat",
   "description": "Number of pending syncs from the followers.",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_PendingRevalidationCount{pod=~\"$cluster(-\\\\d+-\\\\d+-\\\\w+|-\\\\d+)\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "stat",
   "description": "Persistent Volume storage Usage",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-$cluster-.*\"}*100/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-$cluster-.*\"})"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "description": "by cluster,pod selection",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-$cluster-.*\"})"
    }
   ]
  },
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$pod",
   "type": "stat",
   "description": "Number of zookeeper outstanding pod requests",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_OutstandingRequests{pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Container CPU Usage should be < Limit (otherwise performance degradation)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(alias) (label_replace(sum by(pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod$\",container=~\"zookeeper|zookeeper\"}[$interval])),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod$\",container=~\"zookeeper|zookeeper\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "description": "Container Memory Usage should be < Limit (otherwise swapping)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (alias)(label_replace(sum without(area)(jvm_memory_used_bytes{pod=~\"$pod$\",container=~\"zookeeper|zookeeper\"}),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "JVM {{alias}}"
    },
    {
     "expr": "max by (alias)(label_replace(container_memory_working_set_bytes{pod=~\"$pod$\",container=~\"zookeeper|zookeeper\"},\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "K8S {{alias}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod$\",container=~\"zookeeper|zookeeper\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "description": "Storage usage vs capacity",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-$cluster-.*\"})",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "max (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-$cluster-.*\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "description": "Should not exceed 5% otherwise the performance of the application is degraded",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (alias)(label_replace(sum without(gc)(rate(jvm_gc_collection_seconds_sum{pod=~\"$pod$\"}[$interval])),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "{{alias}}"
    },
    { "expr": "vector(0.05)", "legendFormat": "SLA" }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request (since the server was started). Should be < 10s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "expr": "max by (alias)(label_replace(max by(pod)(zookeeper_AvgRequestLatency{pod=~\"$pod\"}),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "Avg {{ alias }}"
    },
    {
     "expr": "max by (alias)(label_replace(max by(pod)(zookeeper_MaxRequestLatency{pod=~\"$pod\"}),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "Max {{ alias }}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process. Should be < 10",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (alias)(label_replace(max by(pod)(zookeeper_OutstandingRequests{pod=~\"$pod\"}),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "timeseries",
   "description": "Zookeeper Packets Received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (alias)(label_replace(rate(zookeeper_PacketsReceived{pod=~\"$pod\"}[$interval]),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "timeseries",
   "description": "Zookeeper Packets Sent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (alias)(label_replace(rate(zookeeper_PacketsSent{pod=~\"$pod\"}[$interval]),\"alias\",\"$1\",\"pod\",\"((strimzi-cluster)-(zookeeper-.*))\"))",
     "legendFormat": "{{ alias }}"
    }
   ]
  }
 ]
}