{
 "title": "Grafana",
 "description": "Grafana Internal Metics Dashboards",
 "tags": [ "grafana" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "2m" }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"grafana-exporter\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Grafana info",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_build_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "SA",
   "type": "stat",
   "description": "Service Availability over past 2 weeks (up and running because targets could be scraped)",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{job=\"grafana-exporter\"}[2w]))"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "Max number of users",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "grafana_stat_active_users" }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_stat_totals_dashboard" }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "stat",
   "description": "Persistent Volume storage usage",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim)(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"grafana-volume-claim\"}*100/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"grafana-volume-claim\"})"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "description": "Persistent Volume storage size",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"grafana-volume-claim\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU Usage in cores",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{container=\"grafana\"})",
     "legendFormat": "Req"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{container=\"grafana\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(sum (rate (container_cpu_usage_seconds_total{container=\"grafana\"}[2m])))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"grafana-exporter\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "max_over_time(go_memstats_alloc_bytes{job=\"grafana-exporter\"}[$interval])",
     "legendFormat": "Max Go"
    },
    {
     "expr": "min_over_time(go_memstats_alloc_bytes{job=\"grafana-exporter\"}[$interval])",
     "legendFormat": "Min Go"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{container=\"grafana\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_memory_bytes{container=\"grafana\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Total Response Statuses",
   "type": "timeseries",
   "description": "http response statusStatus 200 is OK",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_api_response_status_total",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "grafana_page_response_status_total",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "grafana_proxy_response_status_total",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "summary for dashboard get/search duration",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(grafana_api_dashboard_get_milliseconds)",
     "legendFormat": "get"
    },
    {
     "expr": "max(grafana_api_dashboard_search_milliseconds)",
     "legendFormat": "search"
    }
   ]
  }
 ]
}