{
 "title": "Kafka",
 "description": "Kafka Overview using JMX metrics.",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\", container=\"kafka\"},namespace)"
    }
   },
   {
    "name": "Broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_log_size{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "Topic",
    "query": {
     "query": "label_values(kafka_log_logstartoffset{namespace=~\"$namespace\"},topic)"
    }
   },
   {
    "name": "Group",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_sum{topic=~\"$Topic\"},consumergroup)"
    }
   },
   { "name": "interval", "query": "2m" }
  ]
 },
 "panels": [
  { "title": "Broker Info for $Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "WARNING if no active controller",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active Controller",
   "type": "stat",
   "description": "True if the broker is the active controller (it should be only one)",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=~\"$namespace\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "description": "Number of Kafka brokers",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_activecontrollercount{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Partition Replicas",
   "type": "stat",
   "description": "Number of partition replicas for given brokers",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{pod=~\"$Broker$\"})"
    }
   ]
  },
  {
   "title": "Under Replicated",
   "type": "stat",
   "description": "Under replicated partitions",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{pod=~\"$Broker$\", topic=~\"$Topic$\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Number of offline partitions for given brokers",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{pod=~\"$Broker$\"})"
    }
   ]
  },
  {
   "title": "Shrink Rate",
   "type": "stat",
   "description": "Shrink rate of replica manager for given brokers",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrshrinks_total{pod=~\"$Broker$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Expansion Rate",
   "type": "stat",
   "description": "Expansion rate of replica manager for given brokers",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrexpands_total{pod=~\"$Broker$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Purgatory Size",
   "type": "stat",
   "description": "Size of purgatory (delayed operations) for given brokers",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_delayedoperationpurgatory_purgatorysize{delayedOperation=\"Fetch\",pod=~\"$Broker$\"})"
    }
   ]
  },
  {
   "title": "$Broker $Topic Log Size",
   "type": "stat",
   "description": "Log Size by Broker/Topic",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_size{pod=~\"$Broker$\", topic=~\"$Topic$\",topic!=\"\"})"
    }
   ]
  },
  {
   "title": "$Topic Bytes In",
   "type": "stat",
   "description": "Sum of bytes received for given brokers and topics",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{pod=~\"$Broker$\", topic=~\"$Topic$\",topic!=\"\"})"
    }
   ]
  },
  {
   "title": "$Topic Bytes out",
   "type": "stat",
   "description": "Sum of bytes sent for given brokers and topics",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total{pod=~\"$Broker$\", topic=~\"$Topic$\",topic!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Max CPU usage for given brokers",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(process_cpu_seconds_total{pod=~\"$Broker$\",container=\"kafka\"}[$interval]))/max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$Broker$\",container=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "stat",
   "description": "Avg Storage usage for given brokers",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-($Broker)\"}*100/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-($Broker)\"})"
    }
   ]
  },
  {
   "title": "Max Offset Lag",
   "type": "stat",
   "description": "Max Offset Lag for given Consumer Groups",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_lag_sum{consumergroup=~\"$Group\", topic=~\"$Topic\"})"
    }
   ]
  },
  {
   "title": "Max Time Lag",
   "type": "stat",
   "description": "Estimated Max Time Lag for given Consumer Groups, i.e. the time to absorb all kafka queuing, see kafka lag link for more information of the calculation.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_lag{consumergroup=~\"$Group\", topic=~\"$Topic\"})"
    }
   ]
  },
  { "title": "Broker Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Container CPU Usage should be < Limit (otherwise performance degradation)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate (container_cpu_usage_seconds_total{pod=~\"$Broker$\",container=\"kafka\"}[$interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$Broker$\",container=\"kafka\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "description": "Container Memory Usage should be < Limit (otherwise swapping)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod)(container_memory_working_set_bytes{pod=~\"$Broker$\",container=\"kafka\"})",
     "legendFormat": "Mem Used {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$Broker$\",container=\"kafka\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "((max by (pod)(jvm_memory_pool_used_bytes{pod=~\"$Broker$\",container=\"kafka\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor\"}) OR vector(0))+max by(pod)(jvm_memory_pool_used_bytes{pod=~\"$Broker$\",container=\"kafka\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old\"}))",
     "legendFormat": "Heap Used {{pod}}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "description": "Storage usage for given brokers",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim)(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-($Broker)\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-($Broker)\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "description": "Should not exceed 5% in average otherwise the performance of the application is degraded",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(jvm_gc_collection_seconds_sum{pod=~\"$Broker$\",container=\"kafka\"}[$interval]))",
     "legendFormat": "{{pod}}"
    },
    { "expr": "vector(0.05)", "legendFormat": "SLA" }
   ]
  },
  { "title": "Topics & Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Offset Lag per Group",
   "type": "timeseries",
   "description": "Offset Lag for given Consumer Groups",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$Group\", topic=~\"$Topic\"}",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Estimated Time Lag per Group",
   "type": "timeseries",
   "description": "Estimated Time Lag for given Consumer Groups, i.e. the time to absorb all kafka queuing, see kafka lag link for more information of the calculation.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (consumergroup)(kafka_consumergroup_lag{consumergroup=~\"$Group\", topic=~\"$Topic\"})",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Stacked Log Size per Topic",
   "type": "timeseries",
   "description": "Provides the overall storage usage for given topics",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_size{pod=~\"$Broker$\", topic=~\"$Topic$\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In per Topic",
   "type": "timeseries",
   "description": "Messages per second arriving to Kafka for given topics",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic)(rate(kafka_server_brokertopicmetrics_messagesin_total{pod=~\"$Broker$\",topic=~\"$Topic$\",topic!=\"\"}[$interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In per Topic",
   "type": "timeseries",
   "description": "Throughput received for given brokers and topics",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (topic)(rate(kafka_server_brokertopicmetrics_bytesin_total{pod=~\"$Broker$\",topic=~\"$Topic$\",topic!=\"\"}[$interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out per Topic",
   "type": "timeseries",
   "description": "Throughput sent for given brokers and topics",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (topic)(rate(kafka_server_brokertopicmetrics_bytesout_total{pod=~\"$Broker$\",topic=~\"$Topic$\",topic!=\"\"}[$interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Request metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Local request consumer fetch count",
   "type": "timeseries",
   "description": "Local request consumer fetch count for given brokers",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod)(rate(kafka_network_requestmetrics_localtimems{pod=~\"$Broker$\",request=\"FetchConsumer\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Remote request consumer fetch count",
   "type": "timeseries",
   "description": "Remote request consumer fetch count for given brokers",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(kafka_network_requestmetrics_remotetimems{pod=~\"$Broker$\",request=\"FetchConsumer\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request queue consumer fetch count",
   "type": "timeseries",
   "description": "Request queue consumer fetch count for given brokers",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(kafka_network_requestmetrics_requestqueuetimems{pod=~\"$Broker$\",request=\"FetchConsumer\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Fetch requests in Purgatory",
   "type": "timeseries",
   "description": "Fetch requests in Purgatory for given brokers",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations{delayedOperation=\"Fetch\", pod=~\"$Broker$\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Unclean leader election per sec",
   "type": "timeseries",
   "description": "Unclean leader election per sec for given brokers",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod)(rate (kafka_controller_controllerstats_uncleanleaderelections_total{pod=~\"$Broker$\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "#Partition In Synch Replicas",
   "type": "piechart",
   "description": "#Partition In Synch Replicas for given brokers and topics",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic)(kafka_cluster_partition_insyncreplicascount{pod=~\"$Broker$\",topic=~\"$Topic$\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "#Partition Replicas",
   "type": "piechart",
   "description": "#Partition Replicas for given brokers",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kafka_server_replicamanager_partitioncount{pod=~\"$Broker$\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "#Partition Table Offset Lag",
   "type": "piechart",
   "description": "#Partition Table Offset Lag for given brokers and topics. It should empty, when Kafka behaves correctly.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic)(kafka_cluster_partition_laststableoffsetlag{pod=~\"$Broker$\",topic=~\"$Topic$\"})>0",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}