{
 "title": "AWS Glue",
 "description": "Jobs metrics Grouped by all values",
 "tags": [
  "infra",
  "AWS"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "jobName",
    "label": "Spark Job",
    "query": {}
   },
   { "name": "glue", "query": "Glue" },
   {
    "name": "registry",
    "label": "Registry",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Schema Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Schema Version Size",
   "type": "timeseries",
   "description": "The Size of the Schema Version.  \nYou can have up to 10000 schema versions per AWS Region.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Registry": "$registry", "Schema": "*" },
     "metricName": "SchemaVersion.Size",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Schema Version Exhausted",
   "type": "timeseries",
   "description": "You can have up to 10000 schema versions per AWS Region.  \nThe limit is not reached if the value is 0.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Registry": "$registry" },
     "metricName": "SchemaVersion.LimitExhausted",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Success Version",
   "type": "timeseries",
   "description": "Success for getting the schema version",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Registry": "$registry", "Schema": "*" },
     "metricName": "GetSchemaVersion.Success",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Latency Version",
   "type": "timeseries",
   "description": "Latency for getting the schema version",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Registry": "$registry", "Schema": "*" },
     "metricName": "GetSchemaVersion.Latency",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Success Definition",
   "type": "timeseries",
   "description": "Success for getting the schema by definition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Registry": "$registry", "Schema": "*" },
     "metricName": "GetSchemaByDefinition.Success",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Latency Definition",
   "type": "timeseries",
   "description": "Latency for getting the schema by definition",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Registry": "$registry", "Schema": "*" },
     "metricName": "GetSchemaByDefinition.Latency",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Success Creation",
   "type": "timeseries",
   "description": "Success for creating the schema",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Registry": "*" },
     "metricName": "CreateSchema.Success",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Latency Creating",
   "type": "timeseries",
   "description": "Latency for creating the schema",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Registry": "$registry" },
     "metricName": "CreateSchema.Latency",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Success Metatdata",
   "type": "timeseries",
   "description": "Success for putting the schema metadata",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "SchemaVersionId": "*" },
     "metricName": "PutSchemaVersionMetadata.Success",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Latency Metadata",
   "type": "timeseries",
   "description": "Latency for putting schema version Metadata",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "SchemaVersionId": "*" },
     "metricName": "PutSchemaVersionMetadata.Latency",
     "namespace": "AWSSchemaRegistryService",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Spark Job Tasks / Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Driver Completed Stages",
   "type": "timeseries",
   "description": "The number of completed stages in the job.\n\nCan be used to monitor:  \n    Job progress.  \n    Per-stage timeline of job execution,when correlated with other metrics.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "label": "${PROP('Dim.JobName')} ",
     "metricName": "glue.driver.aggregate.numCompletedStages",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Driver Completed Tasks",
   "type": "timeseries",
   "description": "The number of completed tasks in the job.\n\nCan be used to monitor:  \n    Job progress.  \n    Parallelism within a stage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "label": "${PROP('Dim.JobName')} ",
     "metricName": "glue.driver.aggregate.numCompletedTasks",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Driver Failed Tasks",
   "type": "timeseries",
   "description": "The number of failed tasks.\n  \nCan be used to monitor:  \n    Data abnormalities that cause job tasks to fail.  \n    Cluster abnormalities that cause job tasks to fail.  \n    Script abnormalities that cause job tasks to fail.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "label": "${PROP('Dim.JobName')} ",
     "metricName": "glue.driver.aggregate.numFailedTasks",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Driver Killed Tasks",
   "type": "timeseries",
   "description": "The number of tasks killed.  \n\nCan be used to monitor:  \n    Abnormalities in Data Skew that result in exceptions (OOMs) that kill tasks.  \n    Script abnormalities that result in exceptions (OOMs) that kill tasks.  ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "label": "${PROP('Dim.JobName')} ",
     "metricName": "glue.driver.aggregate.numKilledTasks",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Executor System Load",
   "type": "timeseries",
   "description": "The fraction of CPU system load used (scale: 0-1) for ALL executors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dimensions": { "JobName": "$jobName", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.ALL.system.cpuSystemLoad",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Driver System Load",
   "type": "timeseries",
   "description": "The fraction of CPU system load used (scale: 0-1) for the driver.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dimensions": { "JobName": "$jobName", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.driver.system.cpuSystemLoad",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Executor JVM Usage",
   "type": "timeseries",
   "description": "The fraction of memory used by the JVM heap for this executor identified by executorId, or ALL executors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dimensions": { "JobName": "$jobName", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.ALL.jvm.heap.usage",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Driver JVM Usage",
   "type": "timeseries",
   "description": "The fraction of memory used by the JVM heap for this driver.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dimensions": { "JobName": "$jobName", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.driver.jvm.heap.usage",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Executor S3 Read Bytes",
   "type": "timeseries",
   "description": "The number of bytes read from Amazon S3 by ALL executors since the previous report (aggregated by the AWS Glue Metrics Dashboard as the number of bytes read during the previous minute).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.ALL.s3.filesystem.read_bytes",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Driver S3 Read Bytes",
   "type": "timeseries",
   "description": "The number of bytes read from Amazon S3 by the driver since the previous report (aggregated by the AWS Glue Metrics Dashboard as the number of bytes read during the previous minute).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.driver.s3.filesystem.read_bytes",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Executor S3 Write Bytes",
   "type": "timeseries",
   "description": "The number of bytes written from Amazon S3 by ALL executors since the previous report (aggregated by the AWS Glue Metrics Dashboard as the number of bytes written during the previous minute).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.ALL.s3.filesystem.write_bytes",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Driver S3 Write Bytes",
   "type": "timeseries",
   "description": "The number of bytes written from Amazon S3 by the driver since the previous report (aggregated by the AWS Glue Metrics Dashboard as the number of bytes written during the previous minute).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "JobName": "*", "JobRunId": "ALL", "Type": "*" },
     "metricName": "glue.driver.s3.filesystem.write_bytes",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Driver Disk Used",
   "type": "timeseries",
   "description": "The number of megabytes of disk space used across all executors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dimensions": { "JobName": "$jobName", "JobRunId": "ALL", "Type": "*" },
     "label": "${PROP('Dim.JobName')} ",
     "metricName": "glue.driver.BlockManager.disk.diskSpaceUsed_MB",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}