{
 "title": "Logstash",
 "description": "Logstash monitoring via prometheus",
 "tags": [ "Logstash" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "2m" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(logstash_node_pipeline_duration_seconds_total,job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(logstash_node_pipeline_duration_seconds_total{job=~\"$cluster\"},pod)"
    }
   },
   {
    "name": "pipeline",
    "query": {
     "query": "label_values(logstash_node_pipeline_events_in_total{job=~\"$cluster\",pod=~\"$pod\"},pipeline)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(logstash_node_pipeline_duration_seconds_total{job=~\"$cluster\"},container)"
    }
   },
   {
    "name": "in",
    "query": {
     "query": "label_values(logstash_node_plugin_events_out_total{plugin_type=\"input\",container=\"$container\"},plugin)"
    }
   },
   {
    "name": "filter",
    "query": {
     "query": "label_values(logstash_node_plugin_events_out_total{plugin_type=\"filter\",container=\"$container\"},plugin)"
    }
   },
   {
    "name": "out",
    "query": {
     "query": "label_values(logstash_node_plugin_events_out_total{plugin_type=\"output\",container=\"$container\"},plugin)"
    }
   },
   { "name": "index", "query": "elasticsearch" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "description": "Logstash release version",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,logstash_info_node{container=\"logstash\",pod=~\"$pod\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of running Logstash instances",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(count(container_memory_usage_bytes{container=~\"$container\"}))"
    }
   ]
  },
  {
   "title": "Open files",
   "type": "stat",
   "description": "if too many files opened, logstash probably to be scale-up (log messages not unstacked fast enough)",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Pipeline duration",
   "type": "stat",
   "description": "Duration for messages to go through all steps of the pipeline.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(logstash_node_pipeline_duration_seconds_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Events in",
   "type": "stat",
   "description": "Current number of events going IN (log line) treated per second. If < 5 events per seconds, something probably wrong, filebeat containers are not sending logs or logstash is in bad shape (see cpu/mem)",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total{plugin_type=\"input\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Events filtered",
   "type": "stat",
   "description": "Current number of events being FILTERED (in grok, mutate, drop, clone, ruby) treated per secondIf < 20 events per seconds, something probably wrong, in logstash (see cpu/mem)",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total{plugin_type=\"filter\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Events out",
   "type": "stat",
   "description": "Current number of events being going OUT treated per second. If < 5 events per seconds, something probably wrong, Elastic is in bad shape or logstash (see cpu/mem)",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total{plugin_type=\"output\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU usage at container level",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "label_replace(sum by (pod)(rate (container_cpu_usage_seconds_total{pod=~\"$pod\",container=\"logstash\"}[$interval])),\"alias\",\"$1\",\"pod\",\".*-logstash-(.*)\")",
     "legendFormat": "Usage {{alias}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "description": "For more JVM metrics, please check 'Java Pods' dash",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(sum by (pod)(jvm_memory_pool_committed_bytes{pod=~\"$pod\",container=~\"$container\",pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|young|survivor|old\"})+sum by (pod)(jvm_memory_committed_bytes{pod=~\"$pod\",container=~\"$container\",area=\"nonheap\"}))",
     "legendFormat": "Xmx Heap + Stack"
    },
    {
     "expr": "max (container_memory_usage_bytes{pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "Mem Usage K8S"
    },
    {
     "expr": "max(min_over_time(jvm_memory_pool_used_bytes{pod=~\"$pod\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old\"}[1h]))+max(jvm_memory_pool_committed_bytes{pod=~\"$pod\",container=\"$container\",pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor\"} or vector(0))+max(jvm_memory_committed_bytes{pod=~\"$pod\",container=\"$container\", area=\"nonheap\"})",
     "legendFormat": "Used Heap + Stack"
    },
    {
     "expr": "max (kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "description": "Number of Log files opened on Logstash instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum by (pod)(process_open_fds{pod=~\"$pod\",container=~\"$container\"}),\"alias\",\"$1\",\"pod\",\".*-logstash-(.*)\")",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Duration to go through all layers of the logstash pipeline",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pipeline)(rate (logstash_node_pipeline_duration_seconds_total{pod=~\"$pod\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Duration Distribution",
   "type": "piechart",
   "description": "Duration to go through all layers of the logstash pipeline",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (pipeline)(rate (logstash_node_pipeline_duration_seconds_total{pod=~\"$pod\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Events in rate",
   "type": "timeseries",
   "description": "Events/s in rate by type",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(plugin)(rate(logstash_node_plugin_events_out_total{plugin_type=\"input\",plugin=~\"$in\",pod=~\"$pod\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events filtered rate",
   "type": "timeseries",
   "description": "Events/s filtered rate by type",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(plugin)(rate(logstash_node_plugin_events_out_total{plugin_type=\"filter\",plugin=~\"$filter\",pod=~\"$pod\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events out rate",
   "type": "timeseries",
   "description": "Events/s out rate by type",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(plugin)(rate(logstash_node_plugin_events_out_total{plugin_type=\"output\",plugin=~\"$out\",pod=~\"$pod\",container=\"$container\",pipeline=~\"$pipeline\"}[$interval]))",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  { "title": "Plugins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Time spent by plugins",
   "type": "piechart",
   "description": "To identify where time is spent, could be used to measure pipeline improvements",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_duration_seconds_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Failure rate by plugins",
   "type": "piechart",
   "description": "To identify what plugins had errors",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_failures_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events rate by plugins",
   "type": "piechart",
   "description": "Distribution of events",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval])) by (plugin,plugin_type)",
     "legendFormat": "{{plugin}} | type {{plugin_type}}"
    }
   ]
  },
  { "title": "Anomalies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Failure Error rate",
   "type": "timeseries",
   "description": "To identify all processing anomalies",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_failures_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval])) by (plugin,pipeline) > 0",
     "legendFormat": "{{plugin}} plugin failure | {{pipeline}}"
    },
    {
     "expr": "sum(rate(logstash_node_plugin_documents_failures_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval])) by (plugin,pipeline) > 0",
     "legendFormat": "{{plugin}} doc failure | {{pipeline}}"
    },
    {
     "expr": "sum(rate(logstash_node_plugin_bulk_requests_failures_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval])) by (plugin,pipeline) > 0",
     "legendFormat": "{{plugin}} bulk failure | {{pipeline}}"
    },
    {
     "expr": "sum(rate(logstash_node_plugin_bulk_requests_with_errors_total{container=\"$container\",pipeline=~\"$pipeline\"}[$interval])) by (plugin,pipeline) > 0",
     "legendFormat": "{{plugin}} bulk error | {{pipeline}}"
    }
   ]
  }
 ]
}