{
 "title": "Redis",
 "description": "Redis Overview",
 "tags": [ "Redis" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(redis_cluster_enabled{job=~\"redis|redis-app|redis-nbi\"},job)"
    }
   },
   {
    "name": "alias",
    "query": {
     "query": "label_values(redis_up{job=\"$cluster-targets\"}, alias)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits_cpu_cores{container=\"redis\",pod=~\"($alias).*\"},node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\", name=~\"^k8s_.*\",container=\"redis\"}, namespace)"
    }
   },
   {
    "name": "key_group",
    "query": {
     "query": "label_values(redis_key_group_count{job=\"$cluster-targets\"}, key_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Cluster status reported by Elastic Search (green, yellow, red)",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(redis_cluster_enabled{job=\"$cluster-targets\"}) - count(redis_instance_info{job=\"$cluster-targets\",role=\"master\"}) - count(redis_instance_info{job=\"$cluster-targets\",role=\"slave\"})) OR vector(-100)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "maximum redis uptime ",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{job=\"$cluster-targets\",alias=~\"$alias\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "maximum redis version",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by(redis_version)(redis_instance_info{job=\"$cluster-targets\",role=\"master\"})",
     "legendFormat": "{{ redis_version }}"
    }
   ]
  },
  {
   "title": "Master",
   "type": "stat",
   "description": "redis targets master",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(redis_instance_info{job=\"$cluster-targets\",role=\"master\"})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Slaves",
   "type": "stat",
   "description": "redis targets slaves",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_instance_info{job=\"$cluster-targets\",role=\"slave\"})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "description": "redis connected client",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{job=\"$cluster-targets\"})"
    }
   ]
  },
  {
   "title": "Max Clients",
   "type": "stat",
   "description": "redis config maximum clients",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_config_maxclients{job=\"$cluster-targets\"})"
    }
   ]
  },
  {
   "title": "Rejected Connections",
   "type": "stat",
   "description": "Number of connections rejected because of maxclients limit",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_rejected_connections_total{job=\"$cluster-targets\"})"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "stat",
   "description": "Number of clients waiting on a blocking call (BLPOP, BRPOP, BRPOPLPUSH).",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_blocked_clients{job=\"$cluster-targets\"})"
    }
   ]
  },
  {
   "title": "Active DB Keys",
   "type": "stat",
   "description": "Number of active DB keys",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (db)(redis_db_keys{job=\"$cluster-targets\"}>0))"
    }
   ]
  },
  {
   "title": "Cmd Call/s",
   "type": "stat",
   "description": "Commands executed",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{job=\"$cluster-targets\",alias=~\"$alias\"}[10m]))"
    }
   ]
  },
  {
   "title": "Cmd Proc/s",
   "type": "stat",
   "description": "Commands Processed",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{job=\"$cluster-targets\",alias=~\"$alias\"}[10m]))"
    }
   ]
  },
  {
   "title": "Net In",
   "type": "stat",
   "description": "The total number of bytes read from the network",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{job=\"$cluster-targets\",alias=~\"$alias\"}[10m]))"
    }
   ]
  },
  {
   "title": "Net Out",
   "type": "stat",
   "description": "The total number of bytes written to the network",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_net_output_bytes_total{job=\"$cluster-targets\",alias=~\"$alias\"}[10m]))"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "stat",
   "description": "Number of hit ratio",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(irate(redis_keyspace_hits_total{job=\"$cluster-targets\",alias=~\"$alias\"}[10m]))/(sum(irate(redis_keyspace_hits_total{job=\"$cluster-targets\",alias=~\"$alias\"}[10m]))+sum(irate(redis_keyspace_misses_total{job=\"$cluster-targets\",alias=~\"$alias\"}[10m]))))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "CPU usage cores / CPU container limit",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum (rate (redis_cpu_user_seconds_total{job=\"$cluster-targets\",alias=~\"$alias\"}[5m]))+sum (rate (redis_cpu_sys_seconds_total{job=\"$cluster-targets\",alias=~\"$alias\"}[5m])))/max(kube_pod_container_resource_limits_cpu_cores{container=\"redis\"})"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "stat",
   "description": "Redis mem usage / Mem container limit",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"($alias)\",container=\"redis\"})/max(kube_pod_container_resource_limits_memory_bytes{pod=~\"($alias)\",container=\"redis\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "stat",
   "description": "Number of storage usage",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"redis-pvc-($alias)\"}*100/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"redis-pvc-($alias)\"})"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "description": "by redis alias selection",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"redis-pvc-($alias)\"})"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Commands Processed / sec",
   "type": "timeseries",
   "description": "Commands Processed / sec",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (alias)(rate(redis_commands_processed_total{alias=~\"$alias\"}[10m]))",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Items per Alias",
   "type": "timeseries",
   "description": "Total Items per Alias",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{alias=~\"$alias\"}) by (alias)",
     "legendFormat": "{{ alias }} "
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "description": "Command Calls / sec",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cmd,alias)(irate(redis_commands_total{alias=~\"$alias\"} [10m]))",
     "legendFormat": "{{ cmd }} {{ alias}}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "description": "Total Items per DB \ndb0 = oauth | Transform | Write |DIMgr | MO-Manager \ndb1,2,8 = SIE | SPM \ndb4 = TT Ingestion \ndb5 = NX Unit Feeder \ndb9 = NBI \ndb10 = Rest License Manager \n\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{alias=~\"$alias\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  { "title": "Key Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Key Group Memory Distribution",
   "type": "piechart",
   "description": "Memory Usage per DB and Key Group \ndb0 = oauth | Transform | Write |DIMgr | MO-Manager \ndb1,2,8 = SIE | SPM \ndb4 = TT Ingestion \ndb5 = NX Unit Feeder \ndb9 = NBI \ndb10 = Rest License Manager \n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (redis_key_group_memory_usage_bytes{alias=~\"$alias\"}) by (db,key_group)",
     "legendFormat": "{{ db }} | {{ key_group }} "
    }
   ]
  },
  {
   "title": "Key Group Count",
   "type": "timeseries",
   "description": "Total Items per DB and Key Group \ndb0 = oauth | Transform | Write |DIMgr | MO-Manager \ndb1,2,8 = SIE | SPM \ndb4 = TT Ingestion \ndb5 = NX Unit Feeder \ndb9 = NBI \ndb10 = Rest License Manager \n\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_key_group_count{alias=~\"$alias\",key_group=~\"$key_group\"}) by (db,key_group)",
     "legendFormat": "{{ db }} | {{ key_group }} "
    }
   ]
  },
  {
   "title": "Key Group Memory Usage",
   "type": "timeseries",
   "description": "Memory Usage per DB and Key Group \ndb0 = oauth | Transform | Write |DIMgr | MO-Manager \ndb1,2,8 = SIE | SPM \ndb4 = TT Ingestion \ndb5 = NX Unit Feeder \ndb9 = NBI \ndb10 = Rest License Manager \n\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (redis_key_group_memory_usage_bytes{alias=~\"$alias\",key_group=~\"$key_group\"}) by (db,key_group)",
     "legendFormat": "{{ db }} | {{ key_group }} "
    }
   ]
  },
  {
   "title": "Avg Bytes by Key Group Count",
   "type": "timeseries",
   "description": "redis_key_group_memory_usage_bytes / redis_key_group_count\ndb0 = oauth | Transform | Write |DIMgr | MO-Manager \ndb1,2,8 = SIE | SPM \ndb4 = TT Ingestion \ndb5 = NX Unit Feeder \ndb9 = NBI \ndb10 = Rest License Manager \n\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (redis_key_group_memory_usage_bytes{alias=~\"$alias\",key_group=~\"$key_group\"}) by (db,key_group) / avg (redis_key_group_count{alias=~\"$alias\",key_group=~\"$key_group\"}) by (db,key_group)",
     "legendFormat": "{{ db }} | {{ key_group }} "
    }
   ]
  },
  { "title": "Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Cache Hit Ratio should ideally closed to 100%",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{alias=~\"$alias\"}[10m]))/(sum(irate(redis_keyspace_hits_total{alias=~\"$alias\"}[10m]))+sum(irate(redis_keyspace_misses_total{alias=~\"$alias\"}[10m])))",
     "legendFormat": "hits"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "description": "Ideally should a maximum of hits compared to misses",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{alias=~\"$alias\"}[10m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(irate(redis_keyspace_misses_total{alias=~\"$alias\"}[10m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "description": "Expired / Evicted keys/values",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{alias=~\"$alias\"}[10m])) by (alias)",
     "legendFormat": "expired {{alias}}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{alias=~\"$alias\"}[10m])) by (alias)",
     "legendFormat": "evicted {{alias}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "description": "Expiring vs Not-Expiring Keys",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{alias=~\"$alias\"}) - sum (redis_db_keys_expiring{alias=~\"$alias\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{alias=~\"$alias\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Container CPU Usage should be < Limit (otherwise performance degradation)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (alias) (rate (redis_cpu_user_seconds_total{alias=~\"$alias\"}[5m]))+sum by (alias) (rate (redis_cpu_sys_seconds_total{alias=~\"$alias\"}[5m]))",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{container=\"redis\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "if redis max_memory limit =0 it means the maxmemory limit was not specified in redis.conf file, so it is bounded to the container limit",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(redis_memory_used_bytes{alias=~\"$alias\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"($alias)\",container=\"redis\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(redis_memory_used_rss_bytes{alias=~\"$alias\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "max(redis_memory_used_peak_bytes{alias=~\"$alias\"})",
     "legendFormat": "Peak"
    },
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"($alias)-.*\",container=\"redis\"})",
     "legendFormat": "OCP Usage"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "description": "Storage usage vs capacity",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (alias)(label_replace(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"redis-pvc-($alias)\"},\"alias\",\"$1\",\"persistentvolumeclaim\",\"redis-pvc-(.*)\"))",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"redis-pvc-($alias)\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Redis Network I/O",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{alias=~\"$alias\"}[10m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{alias=~\"$alias\"}[10m]))",
     "legendFormat": "output"
    }
   ]
  }
 ]
}