{
 "title": "AWS MSK Kafka",
 "description": "Dashboard for Basic AWS MSK Kafka Cluster metrics visualisation",
 "tags": [
  "AWS",
  "infra"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controller",
   "type": "stat",
   "description": "Only one controller per cluster should be active at any given time.\n",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "ActiveControllerCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Brokers with PartitionCount",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "PartitionCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Brokers with SessionState",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "ZooKeeperSessionState",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "description": "By broker",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "PartitionCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "ZooKeeper Session State",
   "type": "stat",
   "description": "Connection status of broker's ZooKeeper session which may be one of the following: \n\nNOT_CONNECTED: '0.0', \n\nASSOCIATING: '0.1', \n\nCONNECTING: '0.5', \n\nCONNECTEDREADONLY: '0.8', \n\nCONNECTED: '1.0', \n\nCLOSED: '5.0', \n\nAUTH_FAILED: '10.0'.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "ZooKeeperSessionState",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Leader Count",
   "type": "stat",
   "description": "The total number of leaders of partitions per broker, not including replicas.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "LeaderCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Sum Offset Lag",
   "type": "timeseries",
   "description": "The aggregated offset lag for all the partitions in a topic.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "SumOffsetLag",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency",
   "type": "timeseries",
   "description": "The mean latency in milliseconds for Apache ZooKeeper requests from broker.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "ZooKeeperRequestLatencyMsMean",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Global Partition / Global Topic Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "GlobalPartitionCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "GlobalPartitionCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "GlobalTopicCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "GlobalTopicCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "CpuIdle",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Cpu System",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "CpuSystem",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Cpu User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "CpuUser",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "MemoryFree",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "MemoryUsed",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Memory Cached",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "MemoryCached",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Memory Buffered",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "MemoryBuffered",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Data Logs Disk Used ",
     "type": "timeseries",
     "description": "The percentage of disk space used for data logs.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "KafkaDataLogsDiskUsed",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Kafka App Logs Disk Used",
     "type": "timeseries",
     "description": "The percentage of disk space used for application logs.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "KafkaAppLogsDiskUsed",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Root Disk Used",
     "type": "timeseries",
     "description": "The percentage of the root disk used by the broker.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "RootDiskUsed",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Tx Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "p/m" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "NetworkTxPackets",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Tx Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "p/m" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "NetworkTxErrors",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Tx Dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "p/m" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "NetworkTxDropped",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Rx Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "p/m" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "NetworkRxPackets",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Rx Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "p/m" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "NetworkRxErrors",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Rx Dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "p/m" } },
     "targets": [
      {
       "dimensions": { "Cluster Name": "$cluster" },
       "metricName": "NetworkRxDropped",
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}