{
 "title": "Vertical Pod Recommender",
 "description": "A dashboard that monitors Kubernetes and focuses on giving a overview for vertical pod recommender.",
 "tags": [ "VPR" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "NS",
    "query": {
     "query": "label_values(vpr_recommendation_requests_memory_bytes,namespace)"
    }
   },
   {
    "name": "podGroup",
    "label": "Pod Group",
    "query": {
     "query": "label_values(vpr_recommendation_requests_memory_bytes{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(vpr_recommendation_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"$podGroup\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Overall CPU (in vCPUs) for $namespace",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2> Overall CPU in vCPUs</h2></center>"
   }
  },
  {
   "type": "text",
   "description": "Overall Mem for $namespace",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<center><h2> Overall Mem</h2></center>"
   }
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual Req",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Req",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (pod,container)(vpr_recommendation_requests_cpu_cores{namespace=~\"$namespace\"})*sum by (pod,container)(vpr_status_replicas{namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gain Req",
   "type": "stat",
   "description": "Sum Req - Sum Target with taking into accounts replicas",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vpr_gain_requests_cpu_cores{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual Req",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Req",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (pod,container)(vpr_recommendation_requests_memory_bytes{namespace=~\"$namespace\"})*sum by (pod,container)(vpr_status_replicas{namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gain Req",
   "type": "stat",
   "description": "Sum Req - Sum Target",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vpr_gain_requests_memory_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Resource Recommendations (m)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n vpr_recommendation_requests_cpu_cores{\n namespace=~\"$namespace\",\n }\n) by (namespace, pod, kind,replicas,container)*1000",
     "legendFormat": "CPU Target"
    },
    {
     "expr": "max(\n kube_pod_container_resource_requests_cpu_cores{\n namespace=~\"$namespace\",\n }\n) by (namespace, container)*1000",
     "legendFormat": "CPU Target"
    },
    {
     "expr": "max(\n vpr_gain_requests_cpu_cores{\n namespace=~\"$namespace\",\n }\n) by (namespace, pod, kind,replicas,container)*1000",
     "legendFormat": "CPU Target"
    },
    {
     "expr": "max(\n vpr_status_replicas{\n namespace=~\"$namespace\",\n }\n) by (namespace, pod, kind,replicas,container)",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Mem Resource Recommendations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n vpr_recommendation_requests_memory_bytes{\n namespace=~\"$namespace\",\n }\n) by (namespace, pod, kind,replicas,container)",
     "legendFormat": "New Req"
    },
    {
     "expr": "max(\n kube_pod_container_resource_requests_memory_bytes{\n namespace=~\"$namespace\",\n }\n) by (namespace, container)",
     "legendFormat": "Actual Res"
    },
    {
     "expr": "max(\n vpr_gain_requests_memory_bytes{\n namespace=~\"$namespace\",\n }\n) by (namespace, pod, kind,replicas,container)",
     "legendFormat": "Gain"
    },
    {
     "expr": "max(\n vpr_status_replicas{\n namespace=~\"$namespace\",\n }\n) by (namespace, pod, kind,replicas,container)",
     "legendFormat": "Replicas"
    }
   ]
  },
  { "title": "$podGroup / $container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "container" },
  {
   "title": "Actual CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max( kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=~\"$podGroup-.*\", container=~\"$container\" }) by (container)*1000",
     "legendFormat": "Req (m)"
    },
    {
     "expr": "max( kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$podGroup-.*\", container=~\"$container\" }) by (container)*1000",
     "legendFormat": "Limit (m)"
    }
   ]
  },
  {
   "title": "Recommended CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n vpr_recommendation_requests_cpu_cores{\n namespace=~\"$namespace\",\n pod=~\"$podGroup\",\n container=~\"$container\"\n }\n) by (namespace, pod, container, resource)*1000",
     "legendFormat": "Req (m)"
    },
    { "expr": "vector(0)", "legendFormat": "Limit (m)" }
   ]
  },
  {
   "title": "Actual Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n kube_pod_container_resource_requests_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\"\n }\n) by (container)\n",
     "legendFormat": "Req"
    },
    {
     "expr": "max(\n kube_pod_container_resource_limits_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\"\n }\n) by (container)\n",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Recommended Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n vpr_recommendation_requests_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup\",\n container=~\"$container\"\n }\n) by (namespace, pod, container)\n",
     "legendFormat": "Req"
    },
    {
     "expr": "max(\n vpr_recommendation_limits_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup\",\n container=~\"$container\"\n }\n) by (container)",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage, Requests, Limits vs VPR Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(\n vpr_recommendation_requests_cpu_cores{\n namespace=~\"$namespace\",\n pod=~\"$podGroup\",\n container=~\"$container\"\n }\n) by (namespace, pod, container, resource)*1000",
     "legendFormat": "VPR Req"
    },
    {
     "expr": " max(sum(rate(container_cpu_usage_seconds_total{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\",\n container!=\"\",\n container!=\"POD\"\n }[$__rate_interval]\n)) by (pod)*1000)",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(\n kube_pod_container_resource_requests_cpu_cores{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\"\n }\n) by (container)*1000",
     "legendFormat": "Req"
    },
    {
     "expr": "max(\n kube_pod_container_resource_limits_cpu_cores{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\"\n }\n) by (container)*1000",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{pod=~\"$podGroup-.*\",namespace=~\"$namespace\",container=~\"$container\"}[5m]) / rate(container_cpu_cfs_periods_total{pod=~\"$podGroup-.*\",namespace=~\"$namespace\",container=~\"$container\"}[5m]) )",
     "legendFormat": "Throttling %"
    }
   ]
  },
  {
   "title": "Memory Usage, Requests, Limits vs VPR Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n vpr_recommendation_requests_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup\",\n container=~\"$container\"\n }\n) by (namespace, pod, container)",
     "legendFormat": "VPR Req"
    },
    {
     "expr": "max(max (\n container_memory_working_set_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\"\n }\n) by (pod))",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(\n kube_pod_container_resource_requests_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\"\n }\n) by (container)",
     "legendFormat": "Req"
    },
    {
     "expr": "max(\n kube_pod_container_resource_limits_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup-.*\",\n container=~\"$container\"\n }\n) by (container)",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(\n vpr_recommendation_limits_memory_bytes{\n namespace=~\"$namespace\",\n pod=~\"$podGroup\",\n container=~\"$container\"\n }\n) by (namespace, pod, container)",
     "legendFormat": "VPR Limit"
    },
    {
     "expr": "max(vpr_static_jvm_memory_bytes{pod=~\"$podGroup\",container=\"$container\"}) > 0",
     "legendFormat": "VPR JVM Static"
    },
    {
     "expr": "max(vpr_max_after_full_gc_memory_bytes{pod=~\"$podGroup\",container=\"$container\"}) > 0",
     "legendFormat": "VPR JVM Old Gen After Full GC"
    },
    {
     "expr": "max(sum by(pod,container)(jvm_memory_pool_used_bytes{pod=~\"$podGroup-.*\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}))",
     "legendFormat": "JVM Old Gen"
    },
    {
     "expr": "max(sum by(pod,container)(jvm_memory_used_after_gc_bytes{pod=~\"$podGroup-.*\",container=\"$container\",key=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}))",
     "legendFormat": "JVM Old Gen after GC"
    }
   ]
  }
 ]
}