{
 "title": "Pods Java",
 "description": "To troubleshoot heap memory and java internals",
 "tags": [ "Pod" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_memory_pool_used_bytes,pod)"
    }
   },
   {
    "name": "podGroup",
    "query": {
     "query": "label_values(jvm_memory_pool_used_bytes{pod=\"$pod\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(jvm_memory_pool_used_bytes{pod=~\"$container|$pod\"},container)"
    }
   },
   { "name": "interval", "query": "2m" }
  ]
 },
 "panels": [
  { "title": "$container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "container" },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime since container started",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - max(container_start_time_seconds{pod=\"$pod\",container=\"$container\"}))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "JVM Version",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_runtime_info{pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Collector",
   "type": "stat",
   "description": "Type of GC collector (ConcurrentMarkSweep|PS MarkSweep|G1 Old Generation|ZGC|MarkSweepCompact)",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,max by (gc)(jvm_gc_collection_seconds_count{pod=\"$pod\",container=\"$container\",gc=~\"ConcurrentMarkSweep|PS MarkSweep|G1 Old Generation|ZGC|ZGC Cycles|old|end of major GC|end of major GC|MarkSweepCompact|G1 Concurrent GC|ZGC Major Cycles|\"}))",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Young H",
   "type": "stat",
   "description": "Size of the Young Gen. This is available for PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space pools",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_committed_bytes{pod=\"$pod\",container=\"$container\",pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Old H",
   "type": "stat",
   "description": "Size of the Old Gen. This is available for PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_committed_bytes{pod=\"$pod\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})"
    }
   ]
  },
  {
   "title": "Non H",
   "type": "stat",
   "description": "Size of the JVM stack (class structures, runtime constant pool, field, method data, code for methods/constructors/interned strings)",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\",container=\"$container\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Off Heap",
   "type": "stat",
   "description": "Size of the Off Heap (Direct Mem + Mapped Mem) allocated on the RAM directlyDirect mem is when using java.nio.DirectByteBuffer classMapped mem is when using java.nio.MappedByteBuffer class",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_capacity_bytes{pod=\"$pod\",container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Xms",
   "type": "stat",
   "description": "Size of the JVM heap at start-up.",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_pool_init_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"}) OR vector(0))+sum(jvm_memory_pool_init_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})"
    }
   ]
  },
  {
   "title": "Xmx",
   "type": "stat",
   "description": "Size of the JVM heap at target. If memory is needed by the application, the JVM will progressively allocate more memory to the heap until reaching Xmx.",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space\"}) OR vector(0))+sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})"
    }
   ]
  },
  {
   "title": "Xms %",
   "type": "stat",
   "description": "Xms Heap/Limit at start-up\n\nMostly set by construction in memlimit-to-xmx.sh",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "((sum(jvm_memory_pool_init_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"} OR vector(0)))+sum(jvm_memory_pool_init_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})) / sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\",container=~\"^($container)$\"})"
    }
   ]
  },
  {
   "title": "Xmx %",
   "type": "stat",
   "description": "Xmx Heap/Limit at target\n\nMostly set by construction in memlimit-to-xmx.sh",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "((sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space\"} OR vector(0)))+sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})) / sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\",container=~\"^($container)$\"})"
    }
   ]
  },
  {
   "title": "Limit",
   "type": "stat",
   "description": "Current memory limit defined for this container",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\",container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Max Mem Usage %",
   "type": "stat",
   "description": "Used Heap/Heap. OutOfMemoryError Exception if crossing 100%.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "((sum(jvm_memory_pool_used_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"}) OR vector(0))+sum(jvm_memory_pool_used_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})) / ((sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"}) OR vector(0))+sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}))"
    }
   ]
  },
  {
   "title": "OOM",
   "type": "stat",
   "description": "#Number of times this JVM was java.lang.OutOfMemoryError",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "starttime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"java.lang.OutOfMemoryError:\" AND (\"Java heap space\" OR \"GC Overhead limit exceeded\" OR \"Requested array size exceeds VM limit\" OR \"Metaspace\" OR \"Compressed class space\" OR \"stack_trace_with_native_method\") && application:\"$container\" && host:\"$pod\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Stall",
   "type": "stat",
   "description": "Number of ZGC Allocation Stall \ne.g. \n[2022-11-25T00:18:05.712+0100][info ][gc ] GC(127) Garbage Collection (Allocation Stall) 948M(66%)->1034M(72%)",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@logtimestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "starttime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"Garbage Collection (Allocation Stall)\" AND NOT \"start\" AND host:\"$pod\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Old G %",
   "type": "stat",
   "description": "Used (after GC) Old Heap / Old Heap, should not exceed 70% otherwise degradation of java performances because too many or too long GCs (CPU intensive).",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(min(jvm_memory_used_after_gc_bytes{pod=\"$pod\",container=\"$container\",key=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|old|Tenured Gen|ZGC Old Generation\"})/max(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|old|Tenured Gen|ZGC Old Generation\"})) OR (max(min_over_time(jvm_memory_pool_used_bytes{pod=\"$pod\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}[1h]))/max(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}))"
    }
   ]
  },
  {
   "title": "GC Thr",
   "type": "stat",
   "description": "Avg GC Throughput is the percentage of time during which the java process was stopped (time for Full and minor GCs) should be < 5% (> 95% of the time for the application).if GC Throughput > 20% too much time is spent in GC which is killing the application. Does not mean anything for ZGC because the collector by design is low latency.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(max(sum without(gc)(rate(jvm_gc_collection_seconds_sum{pod=~\"$pod\",container=\"$container\",gc!~\"ZGC|ZGC Cycles|ZGC Pauses|ZGC Minor Cycles|ZGC Major Cycles\"}[$interval]))) OR max(sum without(gc)(rate(jvm_gc_collection_milliseconds_sum{pod=\"$pod\",container=\"$container\",gc!~\"ZGC|ZGC Cycles|ZGC Pauses|ZGC Minor Cycles|ZGC Major Cycles\"}[$interval])/1000))) OR (max(sum without(gc)(rate(jvm_gc_collection_seconds_sum{pod=~\"$pod\",gc!~\"ZGC|ZGC Cycles|ZGC Pauses|ZGC Minor Cycles|ZGC Major Cycles\"}[$interval]))) OR max(sum without(gc)(rate(jvm_gc_collection_milliseconds_sum{pod=\"$pod\",container=\"$container\",gc!~\"ZGC|ZGC Cycles|ZGC Pauses|ZGC Minor Cycles|ZGC Major Cycles\"}[$interval])/1000)))"
    }
   ]
  },
  {
   "title": "OOMKilled %",
   "type": "stat",
   "description": "container memory Usage/Limit. OOMKilled is thrown by the container orchestrator if crossing 100%.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pod\",container=~\"^($container)$\"})/ sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\",container=~\"^($container)$\"}) OR (max(container_memory_working_set_bytes{pod=~\"$pod\"})/ sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\"}))"
    }
   ]
  },
  {
   "title": "OOMKilled",
   "type": "stat",
   "description": "#Number of times this pod/container was restarted due to an OOMKilled.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "increase (kube_pod_container_status_restarts_total{pod=\"$pod\",container=\"$container\"}[$__range])*on (pod, container) group_left(reason) kube_pod_container_status_last_terminated_reason{pod=\"$pod\",container=\"$container\",reason=\"OOMKilled\"}"
    }
   ]
  },
  {
   "title": "Throt.",
   "type": "stat",
   "description": "Max CPU Throttling on the period. Should be less than 90% otherwise CPU Limit may be too small.",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_cpu_cfs_throttled_periods_total{pod=~\"$pod\",container=~\"$container\"} / container_cpu_cfs_periods_total{pod=~\"$pod\",container=~\"$container\"} )"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Current number of JVM threads",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{pod=\"$pod\",container=\"$container\"}) OR (sum(jvm_threads_current{pod=\"$pod\"}))"
    }
   ]
  },
  {
   "title": "Files",
   "type": "stat",
   "description": "Number of Open handles (disk files, named pipes, network sockets and devices) by processes in the container. Same as lsof command.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{pod=\"$pod\",container=\"$container\"})"
    }
   ]
  },
  {
   "title": "JVM View",
   "type": "timeseries",
   "description": "Shows OCP limit defined in the container template or site. OCP usage reported by kuberenetes. Xmx Heap close to the Xmx defined as 70% of limitUsed Heap is the max jvm heap usage after GCUsed Heap+NonHeap covering as well the Stack : class structures, runtime constant pool, field, method data, code for methods/constructors/interned stringsYou should have OCP Limit > OCP usage > Xmx Heap+NonHeap > Used HeapAnd No Swap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space\"}) OR vector(0))+sum(jvm_memory_pool_max_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}))",
     "legendFormat": "SLA Xmx Heap"
    },
    {
     "expr": "((sum(jvm_memory_pool_committed_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"}) OR vector(0))+sum(jvm_memory_pool_committed_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}))",
     "legendFormat": "Committed Heap"
    },
    {
     "expr": "((sum(jvm_memory_pool_used_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"}) OR vector(0))+sum(jvm_memory_pool_used_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}))",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$pod\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})",
     "legendFormat": "Old Gen Used"
    },
    {
     "expr": "(min(jvm_memory_used_after_gc_bytes{pod=\"$pod\",container=\"$container\",key=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})) OR (max(min_over_time(jvm_memory_pool_used_bytes{pod=\"$pod\",container=\"$container\",pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"}[1h])))",
     "legendFormat": "Old Gen Used after GC"
    }
   ]
  },
  {
   "title": "K8S View",
   "type": "timeseries",
   "description": "Shows K8S limit defined in the container template or site. K8S usage reported by kuberenetes. Xmx Heap close to the Xmx defined as 70% of limitUsed Heap is the max jvm heap usage after GCUsed Heap+NonHeap covering as well the Stack : class structures, runtime constant pool, field, method data, code for methods/constructors/interned strings \nYou should have K8S Limit > K8S usage > Xmx Heap+NonHeap > Used HeapAnd No Swap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\",container=~\"^($container)$\"})",
     "legendFormat": "SLA K8S Limit"
    },
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pod\",container=~\"^($container)$\"})",
     "legendFormat": "K8S Usage"
    },
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pod\",container=~\"^($container)$\"}) - (((sum(jvm_memory_pool_committed_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor|Eden Space|Survivor Space|ZGC Young Generation\"}) OR vector(0))+sum(jvm_memory_pool_committed_bytes{pod=\"$pod\",container=\"$container\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old|Tenured Gen|ZGC Old Generation\"})))",
     "legendFormat": "Delta K8S - JVM"
    },
    {
     "expr": "(max(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\",container=~\"^($container)$\"}))",
     "legendFormat": "K8S Req"
    }
   ]
  }
 ]
}