{
 "title": "Pods TOP N",
 "description": "TOP N CPU/RAM/Network/Swap Metrics",
 "tags": [ "Pod" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\", name=~\"^k8s_.*\"}, namespace)"
    }
   },
   { "name": "interval", "query": "2m" }
  ]
 },
 "panels": [
  {
   "title": "OOMKilled",
   "type": "timeseries",
   "description": "Containers which received OOMKilled signal because Mem usage > Limit",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{reason=\"OOMKilled\"} > 0",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "TOP N CPU Usage/Limit % => Risk of performance degradation",
   "type": "timeseries",
   "description": "If close to 100% then it means that the application is CPU bounded by the limit.Setting the limit higher will bring better performances of the application.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,(sum by(pod,container,namespace)(rate(container_cpu_usage_seconds_total[$interval])))*100/ sum by(pod,container,namespace)(kube_pod_container_resource_limits_cpu_cores)) > 95",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "TOP N CPU Throttling % => Risk of performance degradation",
   "type": "timeseries",
   "description": "If close to 100% then it means that the application is CPU bounded by the limit.Setting the limit higher will bring better performances of the application.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,(sum by(pod,container,namespace)(rate(container_cpu_cfs_throttled_periods_total[5m]))*100/ sum by(pod,container,namespace)(rate(container_cpu_cfs_periods_total[5m])))) > 95",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "TOP N Memory Usage/Limit % => Risk of OOMKilled",
   "type": "timeseries",
   "description": "Containers which may crash due to OOMKilled signal because Mem usage is closed to Limit",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (pod,container)(container_memory_working_set_bytes)/ sum by (pod,container)(kube_pod_container_resource_limits_memory_bytes) > 0.99",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "TOP N Pods Inbound Traffic",
   "type": "timeseries",
   "description": "Pods that receive the highest network traffic(This metric does not exist at container level)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10,(sum by(pod,container,namespace) (rate (container_network_receive_bytes_total{interface=\"eth0\",pod!=\"\"}[$interval]))))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TOP N Pods Outbound Traffic",
   "type": "timeseries",
   "description": "Pods that send the highest network traffic(This metric does not exist at container level)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10,(sum by(pod,container,namespace) (rate (container_network_transmit_bytes_total{interface=\"eth0\",pod!=\"\"}[$interval]))))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}