{
 "title": "AWS Athena Performances",
 "description": "Amazon Athena is an interactive query service that makes it simple to analyze data directly in Amazon S3 using standard SQL",
 "tags": [
  "infra",
  "AWS"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "workgroup",
    "label": "Work Group",
    "query": {}
   },
   {
    "name": "querystate",
    "label": "Query State",
    "query": {}
   },
   {
    "name": "querytype",
    "label": "Query Type",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": { "Class": "*", "Resource": "*", "Service": "Athena", "Type": "*" },
     "metricName": "CallCount",
     "namespace": "AWS/Usage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "description": "Avg number of bytes that Athena scanned per DML query. For queries that were canceled (either by the users, or automatically, if they reached the limit), this includes the amount of data scanned before the cancellation time. This metric is not reported for DDL queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "QueryState": "$querystate", "QueryType": "$querytype", "WorkGroup": "$workgroup" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/Athena",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Engine Execution Time",
   "type": "timeseries",
   "description": "Avg number of milliseconds that the query took to run.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "QueryState": "$querystate", "QueryType": "$querytype", "WorkGroup": "$workgroup" },
     "metricName": "EngineExecutionTime",
     "namespace": "AWS/Athena",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query Planning Time",
   "type": "timeseries",
   "description": "Avg number of milliseconds that Athena took to plan the query processing flow. This includes the time spent retrieving table partitions from the data source. Note that because the query engine performs the query planning, query planning time is a subset of EngineExecutionTime.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "QueryState": "$querystate", "QueryType": "$querytype", "WorkGroup": "$workgroup" },
     "metricName": "QueryPlanningTime",
     "namespace": "AWS/Athena",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query Queue Time",
   "type": "timeseries",
   "description": "Avg number of milliseconds that the query was in the query queue waiting for resources. Note that if transient errors occur, the query can be automatically added back to the queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "QueryState": "$querystate", "QueryType": "$querytype", "WorkGroup": "$workgroup" },
     "metricName": "QueryQueueTime",
     "namespace": "AWS/Athena",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Service Pre Processing Time",
   "type": "timeseries",
   "description": "Avg number of milliseconds that Athena took to preprocess the query before submitting the query to the query engine.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "QueryState": "$querystate", "QueryType": "$querytype", "WorkGroup": "$workgroup" },
     "metricName": "ServiceProcessingTime",
     "namespace": "AWS/Athena",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Service Processing Time",
   "type": "timeseries",
   "description": "Avg number of milliseconds that Athena took to process the query results after the query engine finished running the query.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "QueryState": "$querystate", "QueryType": "$querytype", "WorkGroup": "$workgroup" },
     "metricName": "ServiceProcessingTime",
     "namespace": "AWS/Athena",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total Execution Time",
   "type": "timeseries",
   "description": "Avg number of milliseconds that Athena took to run a DDL or DML query. TotalExecutionTime includes QueryQueueTime, QueryPlanningTime, EngineExecutionTime, and ServiceProcessingTime.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "QueryState": "$querystate", "QueryType": "$querytype", "WorkGroup": "$workgroup" },
     "metricName": "TotalExecutionTime",
     "namespace": "AWS/Athena",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}