{
 "title": "AWS Bedrock Foundation Models",
 "description": "Visualize Amazon Bedrock metrics",
 "tags": [
  "AWS",
  "infra"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "modelId",
    "label": "Model ID",
    "query": {}
   },
   {
    "name": "logGroupName",
    "label": "Log Group",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Generation",
   "type": "timeseries",
   "description": "Number of tokens/image in the input/output.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ModelId": "$modelId" },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InputTokenCount",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "$modelId" },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "OutputTokenCount",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "$modelId" },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "OutputImageCount",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Invocations Count",
   "type": "timeseries",
   "description": "Number of requests to the Converse, ConverseStream, InvokeModel, and InvokeModelWithResponseStream API operations.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ModelId": "$modelId" },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "timeseries",
   "description": "Latency of the invocations.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ModelId": "$modelId" },
     "label": "Average",
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ModelId": "$modelId" },
     "label": "Minimum",
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    },
    {
     "dimensions": { "ModelId": "$modelId" },
     "label": "Maximum",
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Number of invocations that result in client-side/server-side errors or system throttling.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "dimensions": { "ModelId": "$modelId" },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationClientErrors",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "$modelId" },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationServerErrors",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "$modelId" },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationThrottles",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Invocation Logs",
   "type": "logs",
   "description": "Invocation logs for $modelId.\n\nPlease note that logs >10K are captured.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\nfilter @message like '\"modelId\":\"$modelId\"' |\n sort @timestamp desc |\n limit 20\n ",
     "logGroups": [
      { "arn": "$logGroupName", "name": "$logGroupName" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}