{
 "title": "AWS Bedrock Guardrails",
 "description": "Visualize Amazon Bedrock metrics",
 "tags": [
  "AWS",
  "infra"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Invocations Intervened",
   "type": "timeseries",
   "description": "Number of invocations where the guardrails intervened",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "GuardrailContentSource": "*",
      "GuardrailPolicyType": "*",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationsIntervened",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Invocations Count",
   "type": "timeseries",
   "description": "Number of requests to the ApplyGuardrail API operation",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "GuardrailContentSource": "*",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latencies Input",
   "type": "timeseries",
   "description": "Latency of the invocations.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "GuardrailContentSource": "Input",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "GuardrailContentSource": "Input",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    },
    {
     "dimensions": {
      "GuardrailContentSource": "Input",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Latencies Output",
   "type": "timeseries",
   "description": "Latency of the invocations.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "GuardrailContentSource": "Output",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "GuardrailContentSource": "Output",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    },
    {
     "dimensions": {
      "GuardrailContentSource": "Output",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Text Unit Count",
   "type": "timeseries",
   "description": "Number of text units consumed by the guardrails policies",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "GuardrailContentSource": "*",
      "Operation": "*"
     },
     "logGroups": [
      {
       "accountId": "837071794782",
       "arn": "arn:aws:logs:us-east-1:837071794782:log-group:bedrock-logs:*",
       "name": "bedrock-logs"
      }
     ],
     "metricName": "TextUnitCount",
     "namespace": "AWS/Bedrock/Guardrails",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}