{
 "title": "Nodes",
 "description": "Details of a node",
 "tags": [ "Nodes" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "partition",
    "query": {
     "query": "label_values(node_boot_time_seconds, partition)"
    }
   },
   {
    "name": "server",
    "label": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds{partition=~\"$partition\"}, instance)"
    }
   },
   { "name": "interval", "query": "2m" }
  ]
 },
 "panels": [
  { "title": "Node Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time since last reboot",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "vCPUs",
   "type": "stat",
   "description": "Number of vCPUs (1 physical core = 2 vCPUs) seen at hyper-visor side",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu)(node_cpu_seconds_total{instance=~\"$server\"}))"
    }
   ]
  },
  {
   "title": "vRAM",
   "type": "stat",
   "description": "Total memory seen at hyper-visor side",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Internal Storage",
   "type": "stat",
   "description": "Only Internal disks storage including OS, docker, ephemeral",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",mountpoint=\"/var\"}) "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Server CPU usage ,please consider adding vCPU or nodes if > 75%",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server\"}[$interval]))))*100) / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "description": "Server Mem usage,please consider adding RAM, vRAM or nodes if > 70% to avoid swapping and performance degradation \nOn RHEL 7+, Memory Utilized = ( ( Total - Avail Memory ) / Total LICENSE NOTICE.md README.md VERSION bin conf public scripts tempBakDashToCleanup.json tools 100 ) \nsee \nhttps://www.redhat.com/sysadmin/dissecting-free-command \nhttps://support.site24x7.com/portal/en/kb/articles/how-is-memory-utilization-calculated-for-a-linux-server-monitor",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{instance=~\"$server\"} / node_memory_MemTotal_bytes{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Storage usage,please consider adding storage in partition or PV if > 70% to avoid fragmentation or data loss",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",device!~\"/dev/rbd.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"} - node_filesystem_avail_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",device!~\"/dev/rbd.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"}) / sum(node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",device!~\"/dev/rbd.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"}) "
    }
   ]
  },
  {
   "title": "Node Type",
   "type": "stat",
   "description": "Only available for AWS",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (beta_kubernetes_io_instance_type)(node_boot_time_seconds{instance=~\"$server\"})",
     "legendFormat": "{{ beta_kubernetes_io_instance_type }}"
    }
   ]
  },
  {
   "title": "User/Sys",
   "type": "stat",
   "description": "Ratio CPU User+CPU Nice / CPU System should be at least 2 (when performing at best it should be 10), if < 2 it means the kernel is doing nasty things",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$server\"}[$interval]))+sum by (instance)(rate(node_cpu_seconds_total{mode='nice',instance=~\"$server\"}[$interval]))) / avg(sum by (instance)(rate(node_cpu_seconds_total{mode='system',instance=~\"$server\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "description": "Desired Swap is 0 B, if swapping more than 1GB it degrading the performances because we are using Disk (which is really slow) instead of RAM",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$server\"} - node_memory_SwapFree_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "IO lat R",
   "type": "stat",
   "description": "Read Latency in ms of the different devices of the server, ideally < 5 ms, performance degrades if > 20 ms",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (instance) (rate(node_disk_read_time_seconds_total{instance=~\"$server\"}[$interval])/rate(node_disk_reads_completed_total{instance=~\"$server\"}[$interval]))"
    }
   ]
  },
  {
   "title": "IO lat W",
   "type": "stat",
   "description": "Write Latency in ms of the different devices of the server, ideally < 5 ms, performance degrades if > 20 ms",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (instance) (rate(node_disk_write_time_seconds_total{instance=~\"$server\"}[$interval])/rate(node_disk_writes_completed_total{instance=~\"$server\"}[$interval]))"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "stat",
   "description": "IOPS R+W",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$server\"}[$interval])) + sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$server\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Weighted Load",
   "type": "stat",
   "description": "Load weighted (Load 1 min / number of cores)if >1 it means that the system tries to process more load than the system can handle.More cores needs to be added or better IOs / Network bandwidth.",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$server\"}) / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "stat",
   "description": "Time spent by the CPU waiting for the IOs, if more than 20% it means that IOs have poor performances",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$server\"}[$interval])))*100 / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Highest Partition",
   "type": "stat",
   "description": "The filesystem (partition) with the highest storage usage, 100% means disk full",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(1 - (node_filesystem_avail_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",device!~\"/dev/rbd.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"} / node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",device!~\"/dev/rbd.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"}))"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage on the server,CPU User = CPU used by the application (user+nice), CPU System = CPU used by the kernel, CPU IOWait= CPU waiting for the IOs, CPU Other = CPU used by the IRQ, Steal, Guest",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server\"}[$interval]))))*100) / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$server\"}[$interval]))+sum by (instance)(rate(node_cpu_seconds_total{mode='nice',instance=~\"$server\"}[$interval])))*100 / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(sum by (instance)(rate(node_cpu_seconds_total{mode='system',instance=~\"$server\"}[$interval])))*100 / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$server\"}[$interval])))*100 / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "avg(sum by (instance)(rate(node_cpu_seconds_total{mode='nice',instance=~\"$server\"}[$interval])))*100 / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))",
     "legendFormat": "Nice"
    },
    {
     "expr": "avg(sum (rate(node_cpu_seconds_total{mode!='nice',mode!='idle',mode!='user',mode!='system',mode!='iowait',instance=~\"$server\"}[$interval])))*100 / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "CPU Weighted Load",
   "type": "timeseries",
   "description": "Load weighted (Load 1 min / number of cores)if >1 it means that the system tries to process more load than the system can handle.More cores needs to be added or better IOs / Network bandwidth.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$server\"}) / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))",
     "legendFormat": "load 1m"
    }
   ]
  },
  { "title": "Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage seen at the hyper-visor side. \nThis graph is stacked so that Total = Used + Cached + Free + Buffer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemAvailable_bytes{instance=~\"$server\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server\"} + node_memory_Slab_bytes{instance=~\"$server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "timeseries",
   "description": "It is better to have no swap activity (not using disk as RAM)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_vmstat_pswpin{instance=~\"$server\"}",
     "legendFormat": "Swap In"
    },
    {
     "expr": "node_vmstat_pswpout{instance=~\"$server\"}",
     "legendFormat": "Swap Out"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "% Disk Usage",
   "type": "timeseries",
   "description": "A high Inode usage can generate Evictions of pods due to Disk Pressure event at the node level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"} / node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}*100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Disk Total vs Used",
   "type": "timeseries",
   "description": "Distribution of Disk total and used by mountpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}-node_filesystem_avail_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}",
     "legendFormat": "{{ mountpoint }} used"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}",
     "legendFormat": "{{ mountpoint }} total"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "timeseries",
     "description": "Network throughput",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$server\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[$interval]) > 0",
       "legendFormat": "{{device}} OUT"
      },
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$server\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[$interval]) > 0",
       "legendFormat": "{{device}} IN"
      }
     ]
    },
    {
     "title": "Network issues",
     "type": "timeseries",
     "description": "All kind of errors that can happen at network protocol side",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InCsumErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Icmp_InCsumErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Icmp_InErrors"
      },
      {
       "expr": "irate(Icmp_OutErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Icmp_OutErrors"
      },
      {
       "expr": "irate(node_netstat_IpExt_InCsumErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "IpExt_InCsumErrors"
      },
      {
       "expr": "irate(node_netstat_Udp_InCsumErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Udp_InCsumErrors"
      },
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Udp_InErrors"
      },
      {
       "expr": "irate(node_netstat_Udp_SndbufErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Udp_SndbufErrors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InCsumErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "UdpLite_InCsumErrors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "UdpLite_InErrors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_SndbufErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "UdpLite_SndbufErrors"
      },
      {
       "expr": "irate(node_netstat_Ip_InAddrErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Ip_InAddrErrors"
      },
      {
       "expr": "irate(node_netstat_Ip_InHdrErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Ip_InHdrErrors"
      },
      {
       "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "Udp_RcvbufErrors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "UdpLite_RcvbufErrors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$server\"}[$interval])",
       "legendFormat": "UdpLite_RcvbufErrors"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPLossFailures{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_TCPLossFailures"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPRenoFailures{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_TCPRenoFailures"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSackFailures{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_TCPSackFailures"
      },
      {
       "expr": "irate(node_network_receive_drop{instance=~\"$server\"}[$interval])",
       "legendFormat": "receive_drop"
      },
      {
       "expr": "irate(node_network_transmit_drop{instance=~\"$server\"}[$interval])",
       "legendFormat": "transmit_drop"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_ListenDrops"
      },
      {
       "expr": "irate(node_netstat_TcpExt_LockDroppedIcmps{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_LockDroppedIcmps"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPBacklogDrop{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_TCPBacklogDrop"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPMinTTLDrop{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_TCPMinTTLDrop"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPOFODrop{instance=~\"$server\"}[$interval])",
       "legendFormat": "TcpExt_TCPOFODrop"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process States",
     "type": "timeseries",
     "description": "#processes in each state.\n\nD uninterruptible sleep (usually IO)\n\nI swapped out \n\nR running or runnable (on run queue)\n\nS interruptible sleep (waiting for an event to complete)\n\nT stopped, either by a job control signal or because it is being traced.\n\nW paging (not valid since the 2.6.xx kernel) \n\nX dead (should never be seen)\n\nZ defunct (\"zombie\") process, terminated but not reaped by its parent.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(state) (node_processes_state{instance=~\"$server\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Process Status",
     "type": "timeseries",
     "description": "Blocked is processes waiting for I/O to complete.\n\nRunning is processes in runnable state",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_procs_blocked{instance=\"$server\"}",
       "legendFormat": "blocked"
      },
      {
       "expr": "node_procs_running{instance=\"$server\"}",
       "legendFormat": "running"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "description": "#threads in each state.\n\nD uninterruptible sleep (usually IO)\n\nI swapped out \n\nR running or runnable (on run queue)\n\nS interruptible sleep (waiting for an event to complete)\n\nT stopped, either by a job control signal or because it is being traced.\n\nW paging (not valid since the 2.6.xx kernel) \n\nX dead (should never be seen)\n\nZ defunct (\"zombie\") process, terminated but not reaped by its parent.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(thread_state) (node_processes_threads_state{instance=~\"$server\"})",
       "legendFormat": "{{thread_state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(node_nfs_connections_total{instance=~\"$server\"}[2m])",
       "legendFormat": "connections"
      }
     ]
    },
    {
     "title": "Packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_nfs_packets_total{instance=~\"$server\"}[2m])",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "RPC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(node_nfs_rpc_authentication_refreshes_total{instance=~\"$server\"}[2m])",
       "legendFormat": "Auth"
      },
      {
       "expr": "rate(node_nfs_rpc_retransmissions_total{instance=~\"$server\"}[2m])",
       "legendFormat": "Retransmission"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method,proto)(rate(node_nfs_requests_total{instance=~\"$server\"}[2m]))",
       "legendFormat": "{{method}} ver {{proto}}"
      }
     ]
    },
    {
     "title": "Mean Requests",
     "type": "piechart",
     "description": "Mean requests distribution",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (method)(rate(node_nfs_requests_total{instance=~\"$server\"}[2m]))",
       "legendFormat": "{{method}} ver {{proto}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Inode Usage",
     "type": "timeseries",
     "description": "A high Inode usage can generate Evictions of pods due to Disk Pressure event at the node level",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "0+(100-(node_filesystem_files_free{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}/node_filesystem_files{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"})*100)",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Inode Total vs Used",
     "type": "timeseries",
     "description": "Distribution of Inode total and used by mountpoint",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_files{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}-node_filesystem_files_free{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}",
       "legendFormat": "{{ mountpoint }} used"
      },
      {
       "expr": "node_filesystem_files{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\"}",
       "legendFormat": "{{ mountpoint }} total"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Latency",
     "type": "timeseries",
     "description": "Max IO latency (equivalent to to iostat -x r_await/w_await cols)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "max by (instance) (rate(node_disk_read_time_seconds_total{instance=~\"$server\"}[$interval])/rate(node_disk_reads_completed_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "max Read latency"
      },
      {
       "expr": "max by (instance) (rate(node_disk_write_time_seconds_total{instance=~\"$server\"}[$interval])/rate(node_disk_writes_completed_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "max Write latency"
      }
     ]
    },
    {
     "title": "IO Latency by Device",
     "type": "timeseries",
     "description": "IO latency by devices (equivalent to to iostat -x r_await/w_await cols)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$server\"}[$interval])/rate(node_disk_reads_completed_total{instance=~\"$server\"}[$interval])",
       "legendFormat": "Read {{device}} "
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$server\"}[$interval])/rate(node_disk_writes_completed_total{instance=~\"$server\"}[$interval])",
       "legendFormat": "Write {{device}} "
      }
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS R/W",
     "type": "timeseries",
     "description": "Max IOPS (equivalent to to iostat -x r/s / w/s cols)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$server\"}[$interval])) + sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "- sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "IOPS R/W by Device",
     "type": "timeseries",
     "description": "IOPS by device (equivalent to to iostat -x r/s / w/s cols)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$server\"}[$interval])",
       "legendFormat": "Read {{device}}"
      },
      {
       "expr": "- irate(node_disk_writes_completed_total{instance=~\"$server\"}[$interval])",
       "legendFormat": "Write {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Throughput R/W",
     "type": "timeseries",
     "description": "Max IO Throughput (equivalent to to iostat -x rkB/s wkB/s cols)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_disk_read_bytes_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "- sum by (instance) (irate(node_disk_written_bytes_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum by (instance) (irate(node_disk_read_bytes_total{instance=~\"$server\"}[$interval])) + sum by (instance) (irate(node_disk_written_bytes_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "IO Throughput R/W by Device",
     "type": "timeseries",
     "description": "IO Throughput by Device (equivalent to to iostat -x rkB/s wkB/s cols)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$server\"}[$interval])",
       "legendFormat": "Read {{device}}"
      },
      {
       "expr": "- irate(node_disk_written_bytes_total{instance=~\"$server\"}[$interval])",
       "legendFormat": "Write {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FS cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS Merged",
     "type": "timeseries",
     "description": "IOPS Merged are the extra IOPS produced by the FS caching (for all devices)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_disk_reads_merged_total{instance=~\"$server\"}[$interval])) + sum by (instance)(irate(node_disk_writes_merged_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "Total FS Cache"
      },
      {
       "expr": "sum by (instance)(irate(node_disk_reads_merged_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "FS cache Read"
      },
      {
       "expr": "- sum by (instance)(irate(node_disk_writes_merged_total{instance=~\"$server\"}[$interval]))",
       "legendFormat": "FS cache Write"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "timeseries",
     "description": "Internal metrics for the FS cache, a high Writeback provide good IOPS/Throughput performance, a high Dirty provides bad IOPS/Throughput performance (the data in cache are poorly reused",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=~\"$server\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=~\"$server\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    }
   ]
  }
 ]
}