{
 "title": "AWS FSx",
 "description": "Visualize Amazon FSx metrics",
 "tags": [
  "AWS",
  "infra"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Account", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "Max Storage Usage % @ FS",
   "type": "stat",
   "description": "Max % usage for ALL File Systems based on SSD Tier",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Max Storage Usage % @ Vol",
   "type": "stat",
   "description": "Max % usage for ALL File Systems ALL Volumes",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Max Inodes Usage",
   "type": "stat",
   "description": "The Max percent utilization of ALL file system's Inodes.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Max CPU Usage",
   "type": "stat",
   "description": "The Max percent utilization of ALL file system's File Servers",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"CPUUtilization\"', 'Average', 60))",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Avg IOPS Usage",
   "type": "stat",
   "description": "The Max of the Avg percentage of IOPS utilization of available disk IOPS capacity for ALL file servers. ",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskIopsUtilization\"', 'Average', 60))",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Avg Disk Thru Usage",
   "type": "stat",
   "description": "The Max of the Avg disk throughput between ALL file servers and the primary tier, as a percentage of the provisioned limit determined by throughput capacity. resources. ",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskThroughputUtilization\"', 'Average', 60))",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Avg Net Thru Usage",
   "type": "stat",
   "description": "The Max of the Avg percent utilization of network throughput for ALL file systems. ",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"NetworkThroughputUtilization\"', 'Average', 60))",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Storage Savings %",
   "type": "stat",
   "description": "Max Storage efficiency savings % for ALL FileSystem\n\nStorageEfficiencySavings / (StorageEfficiencySavings+ StorageUsed)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expression": "$A / ($A + $B)", "type": "math" }
   ]
  },
  {
   "title": "Min IOPS Balance",
   "type": "stat",
   "description": "Min IOPS Balance % for ALL FileSystem",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "dimensions": { "VolumeId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskIopsBalance\"', 'Average', 300))",
     "metricEditorMode": 1,
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Min Throughput Balance",
   "type": "stat",
   "description": "Min Throughput Balance % for ALL FileSystem",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "dimensions": { "VolumeId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskThroughputBalance\"', 'Sum', 300))",
     "metricEditorMode": 1,
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Max Read Thru",
   "type": "stat",
   "description": "The Max number of bytes (disk I/O) from any disk reads to ALL file system's primary tier. ",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskReadBytes\"', 'Sum', $period))/$period",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Write Thru",
   "type": "stat",
   "description": "The Max number of bytes (disk I/O) from any disk writes to ALL file system's primary tier. ",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskWriteBytes\"', 'Sum', $period))/$period",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Read IOPS",
   "type": "stat",
   "description": "The Max number of read operations (disk I/O) from ALL file system's primary tier. ",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskReadOperations\"', 'Sum', $period))/$period",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Write IOPS",
   "type": "stat",
   "description": "The Max number of written operations (disk I/O) from ALL file system's primary tier. ",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskWriteOperations\"', 'Sum', $period))/$period",
     "label": "${LABEL}",
     "metricEditorMode": 1,
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Storage Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "description": "The total amount of physical data stored on the file system, on both the primary (SSD) tier and the capacity pool tier. This metric includes savings from storage-efficiency features, such as data compression and deduplication.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DataType": "*", "FileSystemId": "*", "StorageTier": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"StorageUsed\"', 'Average', $period))",
     "label": "${PROP('Dim.DataType')} | ${PROP('Dim.StorageTier')} | ${PROP('Dim.FileSystemId')}",
     "metricName": "StorageUsed",
     "namespace": "AWS/FSx",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "timeseries",
   "description": "The total storage capacity of the primary (SSD) tier.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DataType": "*", "FileSystemId": "*", "StorageTier": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"StorageCapacity\"', 'Sum', $period))",
     "label": "${PROP('Dim.DataType')} | ${PROP('Dim.StorageTier')} | ${PROP('Dim.FileSystemId')}",
     "metricName": "StorageCapacity",
     "namespace": "AWS/FSx",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "timeseries",
   "description": "% usage at File System level for the primary tier",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Storage Savings",
   "type": "timeseries",
   "description": "The bytes saved from storage efficiency features (compression, deduplication, and compaction).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "VolumeId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"StorageEfficiencySavings\"', 'Average', $period))",
     "metricEditorMode": 1,
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Logical Data Stored",
   "type": "timeseries",
   "description": "The total amount of logical data stored on the file system, considering both the SSD tier and the capacity pool tier. This metric includes the total logical size of snapshots and FlexClones, but does not include storage efficiency savings achieved through compression, compaction, and deduplication.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "VolumeId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"LogicalDataStored\"', 'Average', $period))",
     "metricEditorMode": 1,
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Storage Savings %",
   "type": "timeseries",
   "description": "Storage efficiency savings % \n\nStorageEfficiencySavings / (StorageEfficiencySavings+ StorageUsed)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / ($A + $B)", "type": "math" }
   ]
  },
  {
   "title": "Storage Used @ Volume Level",
   "type": "timeseries",
   "description": "The total amount of physical data stored on the file system, on both the primary (SSD) tier and the capacity pool tier. This metric includes savings from storage-efficiency features, such as data compression and deduplication.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DataType": "All", "FileSystemId": "*", "StorageTier": "*", "VolumeId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"StorageCapacity\"', 'Sum', $period))",
     "label": "${PROP('Dim.DataType')} | ${PROP('Dim.StorageTier')} | ${PROP('Dim.FileSystemId')} | ${PROP('Dim.VolumeId')}",
     "metricName": "StorageUsed",
     "namespace": "AWS/FSx",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Capacity @ Volume Level",
   "type": "timeseries",
   "description": "The total storage capacity of the primary (SSD) tier.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "*", "VolumeId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"StorageCapacity\"', 'Sum', $period))",
     "label": "${PROP('Dim.VolumeId')} ",
     "metricName": "StorageCapacity",
     "namespace": "AWS/FSx",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Usage % @ Volume Level",
   "type": "timeseries",
   "description": "% usage at Volume level",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Capacity Pool Read @ Volume Level",
   "type": "timeseries",
   "description": "The number of bytes read (network I/O) from the file system's capacity pool tier.\n\nTo ensure data integrity, ONTAP performs a read operation on the capacity pool immediately after performing a write operation.\n\nThe Sum statistic is the total number of bytes read from the file system's capacity pool tier over a specified period. To calculate capacity pool bytes per second, divide the Sum statistic by the seconds in a specified period. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "*", "VolumeId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"StorageUsed\"', 'Sum', $period))",
     "label": "${PROP('Dim.VolumeId')} ",
     "metricName": "CapacityPoolReadBytes",
     "namespace": "AWS/FSx",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Inodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Inodes Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "*", "VolumeId": "*" },
     "label": "${PROP('Dim.VolumeId')} ",
     "metricName": "FilesCapacity",
     "namespace": "AWS/FSx",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Inodes Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "*", "VolumeId": "*" },
     "label": "${PROP('Dim.VolumeId')} ",
     "metricName": "FilesUsed",
     "namespace": "AWS/FSx",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "description": "The number of bytes (disk I/O) from any disk reads to the file system's primary tier. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "VolumeId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskReadBytes\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "VolumeReadBytes",
       "namespace": "AWS/EBS",
       "period": "$period",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "description": " \t\n\nThe number of bytes (disk I/O) from any disk writes to the file system's primary tier. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "VolumeId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskWriteBytes\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "VolumeReadBytes",
       "namespace": "AWS/EBS",
       "period": "$period",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "description": "The number of read operations (disk I/O) from the file system's primary tier. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskReadOperations\"', 'Sum', $period))/$period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "timeseries",
     "description": "The number of write operations (disk I/O) to the file system's primary tier. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskWriteOperations\"', 'Sum', $period))/$period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "IOPS Usage",
     "type": "timeseries",
     "description": "The disk IOPS between your file server and storage volumes, as a percentage of the primary's tiers provisioned disk IOPS limit. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DiskIopsUtilization\"', 'Average', 60))",
       "label": "${PROP('Dim.FileSystemId')}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Desirable Throughput Capcity",
     "type": "timeseries",
     "description": "As recommended by AWS, you should provision enough throughput capacity to support your workload's read throughput plus twice your workload's write throughput. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      { "expression": "$A + 2 * $B", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "File Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "The percent utilization of the file system's CPU resources. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"CPUUtilization\"', 'Average', 60))",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Disk Throughput Usage",
     "type": "timeseries",
     "description": "The disk throughput between your file server and the primary tier, as a percentage of the provisioned limit determined by throughput capacity. resources. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskThroughputUtilization\"', 'Average', 60))",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "IOPS Usage",
     "type": "timeseries",
     "description": "The percentage of IOPS utilization of available disk IOPS capacity for your file server. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskIopsUtilization\"', 'Average', 60))",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "description": "The percentage of all read requests that are served by data in the file system's RAM and NVMe caches. A higher percentage means that more reads are served by the file system's read caches. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerCacheHitRatio\"', 'Average', 60))",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": " Disk IOPS Balance",
     "type": "timeseries",
     "description": " \t\n\nThe percentage of available burst credits for disk IOPS between your file server and the primary tier. This is valid for file systems that are provisioned with a throughput capacity of 512 MBps or less. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskIopsBalance\"', 'Average', 300))",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": " Disk Throughput Balance",
     "type": "timeseries",
     "description": "The percentage of available burst credits for disk throughput between your file server and the primary tier. This is valid for file systems that are provisioned with a throughput capacity of 512 MBps or less. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"FileServerDiskThroughputBalance\"', 'Average', 300))",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total volumes read (+) and write (-) [bytes/sec]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "VolumeId": "*" },
       "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataReadBytes\"', 'Sum', $period)))/$period",
       "label": "Read",
       "metricEditorMode": 1,
       "metricName": "VolumeReadBytes",
       "namespace": "AWS/EBS",
       "period": "$period",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "alias": "Write",
       "dimensions": { "VolumeId": "*" },
       "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataWriteBytes\"', 'Sum', $period)))/$period",
       "label": "Write",
       "metricEditorMode": 1,
       "metricName": "VolumeReadBytes",
       "namespace": "AWS/EBS",
       "period": "$period",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "description": "The number of bytes (network I/O) from reads by clients to the file system.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "VolumeId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataReadBytes\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "VolumeReadBytes",
       "namespace": "AWS/EBS",
       "period": "$period",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "description": "The number of bytes (network I/O) from writes by clients to the file system.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "VolumeId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataWriteBytes\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "VolumeReadBytes",
       "namespace": "AWS/EBS",
       "period": "$period",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "description": "The count of read operations (network I/O) from reads by clients to the file system.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataReadOperations\"', 'Sum', $period))/$period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "timeseries",
     "description": " \t\n\nThe count of write operations (network I/O) from writes by clients to the file system.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataWriteOperations\"', 'Sum', $period))/$period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Volume READ per instance [total sec in this period]",
     "type": "timeseries",
     "description": "The sum of total time spent within the file system for read operations (network I/O) from clients accessing data in the file system.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataReadOperationTime\"', 'Sum', $period))",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Volume Write per instance [total sec in this period]",
     "type": "timeseries",
     "description": "The sum of total time spent within the file system for fulfilling write operations (network I/O) from clients accessing data in the file system.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"DataWriteOperationTime\"', 'Sum', $period))",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Capacity Pool Read Throughput",
     "type": "timeseries",
     "description": "The number of bytes read (network I/O) from the file system's capacity pool tier.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"CapacityPoolReadBytes\"', 'Sum', $period)) / $period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Capacity Pool Write Throughput",
     "type": "timeseries",
     "description": "The number of bytes written (network I/O) from the file system's capacity pool tier.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"CapacityPoolWriteBytes\"', 'Sum', $period)) / $period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Capacity Pool Read IOPS",
     "type": "timeseries",
     "description": "The number of read operations (network I/O) from the file system's capacity pool tier. This translates to a capacity pool read request. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"CapacityPoolReadOperations\"', 'Sum', $period)) / $period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Capacity Pool Write IOPS",
     "type": "timeseries",
     "description": "The number of write operations (network I/O) from the file system's capacity pool tier. This translates to a capacity pool read request. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"CapacityPoolWriteOperations\"', 'Sum', $period)) / $period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Throughput Usage",
     "type": "timeseries",
     "description": "The percent utilization of network throughput for the file system. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 209 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"NetworkThroughputUtilization\"', 'Average', 60))",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Metadata IOPS",
     "type": "timeseries",
     "description": "The count of metadata operations (network I/O) by clients to the file system.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 209 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/FSx,FileSystemId} MetricName=\"MetadataOperations\"', 'Sum', $period))/$period",
       "label": "${LABEL}",
       "metricEditorMode": 1,
       "period": "$period",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}