{
 "title": "ElasticSearch",
 "description": "ElasticSearch Overview",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,elastic_cluster)"
    }
   },
   { "name": "type", "label": "type", "query": "client,data,master" },
   { "name": "interval", "label": "Interval", "query": "2m" },
   {
    "name": "name",
    "label": "pod",
    "query": {
     "query": "label_values(elasticsearch_process_cpu_percent{name=~\".*($type).*\",elastic_cluster=\"$cluster\"},name)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(elasticsearch_indices_segment_count_total{elastic_cluster=\"$cluster\"},index)"
    }
   },
   {
    "name": "node",
    "label": "node (info)",
    "query": {
     "query": "label_values(container_memory_swap{pod=~\"$name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Cluster status reported by Elastic Search (green, yellow, red)",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_status{color=\"green\",elastic_cluster=\"$cluster\"})-1*sum(elasticsearch_cluster_health_status{color=\"yellow\",elastic_cluster=\"$cluster\"})-2*sum(elasticsearch_cluster_health_status{color=\"red\",elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Elastic Search Version",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,elasticsearch_clusterinfo_version_info{elastic_cluster=\"$cluster\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Master",
   "type": "stat",
   "description": "#Master Nodes : should be 3 masters to have good performances and availability at all time",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_process_cpu_percent{es_master_node=\"true\",elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "including master/data/client nodes",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_nodes{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data",
   "type": "stat",
   "description": "#Data Nodes : should be at least 3",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_data_nodes{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Indices",
   "type": "stat",
   "description": "equivalent of tables for a DB",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_indices_segment_count_total{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "description": "1 means there is 1 copy in addition to primary so there are 2 shards in total",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes_total{elastic_cluster=\"$cluster\"})/sum(elasticsearch_indices_store_size_bytes_primary{elastic_cluster=\"$cluster\"})-1"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "description": "Pending Tasks : cluster-level changes (e.g. create index, update mapping, allocate or fail shard) which have not yet been executed.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Docs",
   "type": "stat",
   "description": "Docs",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Indices Size",
   "type": "stat",
   "description": "Sum of all indices including replicas",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes_total{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Shards", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 0, "y": 3 }, "options": { "content": "\n\n\n" } },
  { "title": "Performances", "type": "text", "gridPos": { "h": 1, "w": 14, "x": 10, "y": 3 }, "options": { "content": "\n\n\n" } },
  {
   "title": "Active",
   "type": "stat",
   "description": "Number of cluster active shards",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Primary",
   "type": "stat",
   "description": "Number of cluster active primary shards",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_primary_shards{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Initializing",
   "type": "stat",
   "description": "Number of cluster initializing shards",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_initializing_shards{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Relocating",
   "type": "stat",
   "description": "Number of cluster relocating shards",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_relocating_shards{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unassigned",
   "type": "stat",
   "description": "Number of cluster delayed unassigned shards",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_delayed_unassigned_shards{elastic_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Rejections",
   "type": "stat",
   "description": "Max number of rejected bulk operations, means Elastic is saturated if > 30 (probably needs to scale up/out or decrease replicas)",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum (irate(elasticsearch_thread_pool_rejected_count{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$interval:])"
    }
   ]
  },
  {
   "title": "Avg Query",
   "type": "stat",
   "description": "Average query time in Elastic, should not exceed 50ms",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max(rate(elasticsearch_indices_search_query_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$interval:])"
    }
   ]
  },
  {
   "title": "Max Query",
   "type": "stat",
   "description": "Max query time in Elastic, should not exceed 200ms",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(rate(elasticsearch_indices_search_query_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$interval:])"
    }
   ]
  },
  {
   "title": "Avg Ingestion rate by DN",
   "type": "stat",
   "description": "Avg #Docs per seconds issued to ElasticSearch per DN",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(avg(rate(elasticsearch_indices_docs{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval])) [$interval:])"
    }
   ]
  },
  {
   "title": "Max Ingestion rate by DN",
   "type": "stat",
   "description": "Max #Docs per seconds issued to ElasticSearch per DN",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(rate(elasticsearch_indices_docs{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval])) [$__interval:]) <100000"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Red Indices",
     "type": "timeseries",
     "description": "List of RED indices in Elasticsearch. Generally, index is red due to unassigned/relocating primary shards. Check associated panels for more info.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (index)(es_cluster_health_indices_status_red{index=~\"$index\"}) > 0",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Yellow Indices",
     "type": "timeseries",
     "description": "List of Yellow indices in Elasticsearch. Generally, index is red due to unassigned/relocating replica shards. Check associated panels for more info.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (index)(es_cluster_health_indices_status_yellow{index=~\"$index\"}) > 0",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Unassigned Shards",
     "type": "timeseries",
     "description": "Count of unassigned shards for indices. Data Node unavailibility, bad Routing or Allocation rules, shard count limit are the primary cause of unassigned shards in the cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (index)(es_cluster_health_indices_unassigned_shards{index=~\"$index\"}) > 0",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Relocating Shards",
     "type": "timeseries",
     "description": "Count of relocating shards for indices. Relocation is a normal process in Elasticsearch cluster. It may take time to complete.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (index)(es_cluster_health_indices_relocating_shards{index=~\"$index\"}) > 0",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Initializing Shards",
     "type": "timeseries",
     "description": "Count of initializing shards for indices.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (index)(es_cluster_health_indices_initializing_shards{index=~\"$index\"}) > 0",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Shard Count",
     "type": "table",
     "description": "Number of different shard for selected index",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "max by (index)(es_cluster_health_indices_active_shards{index=~\"$index\"})",
       "legendFormat": "Active Shards"
      },
      {
       "expr": "max by (index) (es_cluster_health_indices_active_primary_shards{index=~\"$index\"})",
       "legendFormat": "Primary Shards"
      },
      {
       "expr": "max by (index) (es_cluster_health_indices_number_of_replicas{index=~\"$index\"})",
       "legendFormat": "Replica"
      }
     ]
    }
   ]
  },
  {
   "title": "Performances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Time",
     "type": "timeseries",
     "description": "Query Time by Node per selection",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(rate(elasticsearch_indices_search_query_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Query Time Index Distribution",
     "type": "piechart",
     "description": "Distribution by index",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max_over_time(rate(elasticsearch_index_stats_search_query_time_seconds_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]) [$__interval:]) > 0",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Query Time Index",
     "type": "timeseries",
     "description": "Query Time by Index per selection",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max_over_time(rate(elasticsearch_index_stats_search_query_time_seconds_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]) [$__interval:]) > 0",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Indexing Time",
     "type": "timeseries",
     "description": "Indexing Time by Node per selection",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(rate(elasticsearch_indices_indexing_index_time_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Indexing Time Index Distribution",
     "type": "piechart",
     "description": "Distribution by index",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "rate(elasticsearch_index_stats_indexing_index_time_seconds_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]) > 0",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Indexing Time Index",
     "type": "timeseries",
     "description": "Indexing Time by Index per selection",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(elasticsearch_index_stats_indexing_index_time_seconds_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]) > 0",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Docs",
     "type": "timeseries",
     "description": "Stacked graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(sum by (name)(elasticsearch_indices_docs{name=~\"$name\",elastic_cluster=\"$cluster\"}),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{ alias }}"
      }
     ]
    },
    {
     "title": "Index Docs Distribution",
     "type": "piechart",
     "description": "Distribution by index",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " elasticsearch_indices_docs_primary{index=~\"$index\",elastic_cluster=\"$cluster\"}",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Index Docs",
     "type": "timeseries",
     "description": "Stacked graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": " elasticsearch_indices_docs_primary{index=~\"$index\",elastic_cluster=\"$cluster\"}",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Docs Ingestion rate",
     "type": "timeseries",
     "description": "Rate of inserted documents for selected nodes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(avg by (name)(rate(elasticsearch_indices_docs{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval])) <100000,\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Usage %",
     "type": "timeseries",
     "description": "Elastic search get in degraded mode when > 85% usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "vector(0.85)", "legendFormat": "SLA" },
      {
       "expr": "label_replace(max by (persistentvolumeclaim)(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-$name\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-$name\"}),\"alias\",\"$1\",\"persistentvolumeclaim\",\".*-elasticsearch-(.*)\")",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Index Used Distribution",
     "type": "piechart",
     "description": "Distribution",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_indices_store_size_bytes_total{index=~\"$index\",elastic_cluster=\"$cluster\"}",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Node Storage Size",
     "type": "timeseries",
     "description": "Stacked graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(max by (persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-$name\"}),\"alias\",\"$1\",\"persistentvolumeclaim\",\".*-elasticsearch-(.*)\")",
       "legendFormat": "{{ alias }}"
      }
     ]
    },
    {
     "title": "Node Used",
     "type": "timeseries",
     "description": "Stacked graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(max by (persistentvolumeclaim)(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-$name\"}),\"alias\",\"$1\",\"persistentvolumeclaim\",\".*-elasticsearch-(.*)\")",
       "legendFormat": "{{ alias }}"
      }
     ]
    },
    {
     "title": "Index Used",
     "type": "timeseries",
     "description": "Stacked graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (index)(elasticsearch_indices_store_size_bytes_total{index=~\"$index\",elastic_cluster=\"$cluster\"})",
       "legendFormat": "{{ index }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops Time",
     "type": "timeseries",
     "description": "Duration of batch Elastic operations",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_indexing_index_time_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "indexing"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_search_query_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "query"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_search_fetch_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "fetch"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_merges_total_time_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "merges"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_refresh_time_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "refresh"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_flush_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "flush"
      }
     ]
    },
    {
     "title": "Ops Time Distribution",
     "type": "piechart",
     "description": "Distribution",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_indexing_index_time_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "indexing"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_search_query_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "query"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_search_fetch_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "fetch"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_merges_total_time_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "merges"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_refresh_time_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "refresh"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_flush_time_seconds{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "flush"
      }
     ]
    },
    {
     "title": "Ops Rate",
     "type": "timeseries",
     "description": "Batch Elastic operations per second",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(elasticsearch_indices_indexing_index_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "indexing"
      },
      {
       "expr": "sum(irate(elasticsearch_indices_search_query_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "query "
      },
      {
       "expr": "sum(irate(elasticsearch_indices_search_fetch_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "fetch"
      },
      {
       "expr": "sum(irate(elasticsearch_indices_merges_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "merges"
      },
      {
       "expr": "sum(irate(elasticsearch_indices_refresh_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "refresh"
      },
      {
       "expr": "sum(irate(elasticsearch_indices_flush_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "flush"
      }
     ]
    },
    {
     "title": "Ops Rate Distribution",
     "type": "piechart",
     "description": "Distribution",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_indexing_index_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "indexing"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_search_query_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "query "
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_search_fetch_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "fetch"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_merges_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "merges"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_refresh_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "refresh"
      },
      {
       "expr": "avg_over_time(sum(rate(elasticsearch_indices_flush_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval]))[$__interval:])",
       "legendFormat": "flush"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations TOP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOP 10 Get",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_get_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Fetch",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_search_fetch_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Flush",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_flush_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Indexing",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_indexing_index_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Indexing Delete",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_indexing_delete_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Merge",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_merge_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Refresh",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_refresh_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Search Query",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_search_query_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Search Scroll",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_search_scroll_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Search Suggest",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_search_suggest_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "TOP 10 Warmer",
     "type": "piechart",
     "description": "Distribution of mean values for time selection",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,rate(elasticsearch_index_stats_warmer_total{index=~\"$index\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ index }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active",
     "type": "timeseries",
     "description": "Active thread pools",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type)(elasticsearch_thread_pool_active_count{name=~\"$name\",type!=\"management\",elastic_cluster=\"$cluster\"})",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Queued",
     "type": "timeseries",
     "description": "Queuing threads, should be ideally really small (from 1 to 5)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type)(elasticsearch_thread_pool_queue_count{name=~\"$name\",type!=\"management\",elastic_cluster=\"$cluster\"})",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Completed",
     "type": "timeseries",
     "description": "Completed threads pools",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type)(irate(elasticsearch_thread_pool_completed_count{name=~\"$name\",type!=\"management\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Rejected",
     "type": "timeseries",
     "description": "Rejected pool threads, ideally should be close to 0.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type)(irate(elasticsearch_thread_pool_rejected_count{name=~\"$name\",type!=\"management\",elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "CPU Usage for selection",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(sum by(name)(rate(elasticsearch_process_cpu_seconds_total{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval])),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"^$name$\"})",
       "legendFormat": "Max Limit"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "timeseries",
     "description": "For more JVM metrics, please check 'Java Pods' dash",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(((max by (name)(jvm_memory_pool_used_bytes{pod=~\"$name\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor\"}) OR vector(0))+max by (name)(jvm_memory_pool_used_bytes{pod=~\"$name\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old\"})),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "Heap Used {{alias}}"
      },
      {
       "expr": "((max(jvm_memory_pool_max_bytes{pod=~\"$name\", pool=~\"PS Eden Space|G1 Eden Space|PS Survivor Space|G1 Survivor Space|Par Eden Space|Par Survivor Space|young|survivor\"}) OR vector(0))+max(jvm_memory_pool_max_bytes{pod=~\"$name\", pool=~\"PS Old Gen|G1 Old Gen|CMS Old Gen|ZHeap|old\"}))",
       "legendFormat": "SLA Xmx Heap"
      },
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"$name\"})",
       "legendFormat": "Max OCP Usage"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"^$name$\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "timeseries",
     "description": "Should not exceed 5% in average otherwise the performance of the application is degraded",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(sum without(gc)(rate(jvm_gc_collection_seconds_sum{name=~\"$name\",elastic_cluster=\"$cluster\"}[$interval])),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{ alias }}"
      },
      { "expr": "sum(vector(0.05))", "legendFormat": "SLA GC Throughput" }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Cache Size",
     "type": "timeseries",
     "description": "Query Cache Size",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(avg by (name)(elasticsearch_indices_query_cache_memory_size_bytes{name=~\"$name\",elastic_cluster=\"$cluster\"}),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{ alias }}"
      }
     ]
    },
    {
     "title": "Query Cache Hit Ratio",
     "type": "timeseries",
     "description": "Query Cache Hit Ratio",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (index)(rate(elasticsearch_index_stats_query_cache_hits_total{elastic_cluster=\"$cluster\"}[$interval]))/sum by (index)(rate(elasticsearch_index_stats_query_cache_hits_total{elastic_cluster=\"$cluster\"}[$interval])+rate(elasticsearch_index_stats_query_cache_misses_total{elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Request Cache Size",
     "type": "timeseries",
     "description": "Request Cache Size",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(avg by (name)(elasticsearch_indices_request_cache_memory_size_bytes{name=~\"$name\",elastic_cluster=\"$cluster\"}),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{ alias }}"
      }
     ]
    },
    {
     "title": "Request Cache Hit Ratio",
     "type": "timeseries",
     "description": "should be closed to 100%",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (index)(rate(elasticsearch_index_stats_request_cache_hits_total{elastic_cluster=\"$cluster\"}[$interval]))/sum by (index)(rate(elasticsearch_index_stats_request_cache_hits_total{elastic_cluster=\"$cluster\"}[$interval])+rate(elasticsearch_index_stats_request_cache_misses_total{elastic_cluster=\"$cluster\"}[$interval]))",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Field Data Memory Size",
     "type": "timeseries",
     "description": "Field Data Memory Size",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(avg by (name)(elasticsearch_indices_fielddata_memory_size_bytes{name=~\"$name\",elastic_cluster=\"$cluster\"}),\"alias\",\"$1\",\"name\",\"elasticsearch-(.*)\")",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  }
 ]
}