{
 "title": "Nodes TOP N",
 "description": "Check nodes with the TOP resource usage",
 "tags": [ "Nodes" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "partition",
    "query": {
     "query": "label_values(node_boot_time_seconds, partition)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(node_boot_time_seconds{partition=~\"$partition\"}, instance)"
    }
   },
   { "name": "TOP", "label": "TOP", "query": "3,5,10,20,50" },
   {
    "name": "device",
    "query": {
     "query": "label_values(container_fs_usage_bytes{job=~\"kubernetes-.*\", instance=~\"$server\", id=\"/\"}, device)"
    }
   },
   { "name": "interval", "query": "2m" },
   {
    "name": "slow_cpu",
    "query": {
     "query": "query_result(topk($TOP, max((((count by (instance) (count by (cpu,instance)(node_cpu_seconds_total{instance=~\"$server\"}))) - avg by (instance)(sum by (mode,instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server\"}[${__range_s}s]))))*100) / count by (instance)(count by (cpu,instance)(node_cpu_seconds_total{instance=~\"$server\"}))) by (instance)))"
    }
   },
   {
    "name": "slow_iops",
    "query": {
     "query": "query_result(topk($TOP, sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$server\"}[${__range_s}s])) + sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$server\"}[${__range_s}s]))))"
    }
   },
   {
    "name": "slow_latencyR",
    "query": {
     "query": "query_result(topk($TOP, max by (instance) (rate(node_disk_read_time_seconds_total{instance=~\"$server\"}[${__range_s}s])/rate(node_disk_reads_completed_total{instance=~\"$server\"}[${__range_s}s]))))"
    }
   },
   {
    "name": "slow_latencyW",
    "query": {
     "query": "query_result(topk($TOP, max by (instance) (rate(node_disk_write_time_seconds_total{instance=~\"$server\"}[${__range_s}s])/rate(node_disk_writes_completed_total{instance=~\"$server\"}[${__range_s}s]))))"
    }
   },
   {
    "name": "slow_Load",
    "query": {
     "query": "query_result(topk($TOP,avg by (instance)(node_load1{instance=~\"$server\"})/ count by (instance) (count by (cpu,instance) (node_cpu_seconds_total) )))"
    }
   },
   {
    "name": "slow_Mem",
    "query": {
     "query": "query_result(topk($TOP, 1-(node_memory_MemAvailable_bytes{instance=~\"$server\"} / node_memory_MemTotal_bytes{instance=~\"$server\"})))"
    }
   },
   {
    "name": "slow_Partition",
    "query": {
     "query": "query_result(topk($TOP, 1 - (node_filesystem_avail_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",device!~\"/dev/rbd.*|/dev/mapper.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"} / node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$server\",fstype=~\"xfs\",device!~\"/dev/rbd.*|/dev/mapper.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"})))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TOP $TOP used CPU",
   "type": "timeseries",
   "description": "Server CPU usage ,please consider adding vCPU or nodes if > 75%",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max((((count by (instance) (count by (cpu,instance)(node_cpu_seconds_total{instance=~\"$slow_cpu\"}))) - avg by (instance)(sum by (mode,instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$slow_cpu\"}[$interval]))))*100) / count by (instance)(count by (cpu,instance)(node_cpu_seconds_total{instance=~\"$slow_cpu\"}))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TOP $TOP Weighted Load 1m",
   "type": "timeseries",
   "description": "Load weighted (Load 1 min / number of cores)if >1 it means that the system tries to process more load than the system can handle.More cores needs to be added or better IOs / Network bandwidth.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($TOP,avg by (instance)(node_load1{instance=~\"$slow_Load\"})/ count by (instance) (count by (cpu,instance) (node_cpu_seconds_total) ))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TOP $TOP used Mem",
   "type": "timeseries",
   "description": "Server Mem usage,please consider adding RAM, vRAM or nodes if > 70% to avoid swapping and performance degradation",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($TOP, 1-(node_memory_MemAvailable_bytes{instance=~\"$slow_Mem\"} / node_memory_MemTotal_bytes{instance=~\"$slow_Mem\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "Network throughput",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($TOP,max by(instance)(irate(node_network_transmit_bytes_total{instance=~\"$server\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[$interval])))",
     "legendFormat": "OUT | {{instance}}"
    },
    {
     "expr": "topk($TOP,max by(instance)(irate(node_network_receive_bytes_total{instance=~\"$server\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[$interval])))",
     "legendFormat": "IN | {{instance}}"
    }
   ]
  },
  {
   "title": "TOP $TOP IOPS",
   "type": "timeseries",
   "description": "IOPS R+W",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($TOP, sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$slow_iops\"}[$interval])) + sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$slow_iops\"}[$interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TOP $TOP used Filesystems",
   "type": "timeseries",
   "description": "Server partition usage,please consider adding storage if > 70% to avoid fragmentation for performance degradation and avoiding disk full",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($TOP, 1 - (node_filesystem_avail_bytes{job=\"kubernetes-node-exporter\",instance=~\"$slow_Partition\",fstype=~\"xfs\",device!~\"/dev/rbd.*|/dev/mapper.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"} / node_filesystem_size_bytes{job=\"kubernetes-node-exporter\",instance=~\"$slow_Partition\",fstype=~\"xfs\",device!~\"/dev/rbd.*|/dev/mapper.*\",mountpoint!~\".*/(nfs|ebs|rbd)/.*\"}))",
     "legendFormat": "{{instance}} | {{mountpoint}} "
    }
   ]
  },
  {
   "title": "TOP $TOP IO latency Max R",
   "type": "timeseries",
   "description": "Read Latency in ms of the different devices of the server, ideally < 5 ms, performance degrades if > 20 ms",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($TOP, max by (instance) (rate(node_disk_read_time_seconds_total{instance=~\"$slow_latencyR\"}[$interval])/rate(node_disk_reads_completed_total{instance=~\"$slow_latencyR\"}[$interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TOP $TOP IO latency Max W",
   "type": "timeseries",
   "description": "Write Latency in ms of the different devices of the server, ideally < 5 ms, performance degrades if > 20 ms",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($TOP, max by (instance) (rate(node_disk_write_time_seconds_total{instance=~\"$slow_latencyW\"}[$interval])/rate(node_disk_writes_completed_total{instance=~\"$slow_latencyW\"}[$interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}