{
 "title": "AWS Apache Airflow (MWAA)",
 "description": "Apache Airflow is an open-source workflow management platform for data engineering pipelines.",
 "tags": [
  "infra",
  "AWS"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "dag",
    "label": "DAG",
    "query": {}
   },
   {
    "name": "dag_file",
    "label": "Dag File",
    "query": {}
   },
   {
    "name": "task",
    "label": "Task",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Avg Cpu usage of scheduler, worker, and web server Airflow components",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Cluster": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Mem Utilization",
   "type": "timeseries",
   "description": "Avg  Mem usage of scheduler, worker, and web server Airflow components",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metricName": "MemoryUtilization",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Avg Cpu usage of scheduler, worker, and web server Airflow components",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DatabaseRole": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "description": "Maximum Memory that can be freed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "FreeableMemory",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "description": "Avg Read Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "metricName": "ReadLatency",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "description": "Avg Write Latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "metricName": "WriteLatency",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "description": "Avg Read IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "metricName": "ReadIOPS",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "description": "Avg Write IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "metricName": "WriteIOPS",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "description": "Maximum Queue Depth",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "description": "Avg Database Connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "DatabaseConnections",
     "namespace": "AWS/MWAA",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Queue / ALB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Tasks",
     "type": "timeseries",
     "description": "Avg Running Tasks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "RunningTasks",
       "namespace": "AWS/MWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Queued Tasks",
     "type": "timeseries",
     "description": "Max Queued Tasks",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "QueuedTasks",
       "namespace": "AWS/MWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Active Connection Count",
     "type": "timeseries",
     "description": "Avg Active Connection Count  \nApplication Load Balancer metrics apply to the web servers running in your environment. Amazon MWAA uses these metrics to for scaling your web servers based on the amount of traffic.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "ActiveConnectionCount",
       "namespace": "AWS/MWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Oldest Task Age",
     "type": "timeseries",
     "description": "Approximate Age Of Oldest Task in s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "metricName": "ApproximateAgeOfOldestTask",
       "namespace": "AWS/MWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "DAG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "DAG Duration Success",
     "type": "timeseries",
     "description": "dagrun.duration.success.{dag_id}  \nMilliseconds taken for a DagRun to reach success state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag" },
       "metricName": "DAGDurationSuccess",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DAG Duration Failed",
     "type": "timeseries",
     "description": "dagrun.duration.failed.{dag_id}  \nMilliseconds taken for a DagRun to reach failed state",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag" },
       "metricName": "DAGDurationFailed",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DAG Dependency Check",
     "type": "timeseries",
     "description": "dagrun.dependency-check.<dag_id>  \nMilliseconds taken to check DAG dependencies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag" },
       "metricName": "DAGDependencyCheck",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DAG Schedule Delay",
     "type": "timeseries",
     "description": "dagrun.schedule_delay.<dag_id>\nMilliseconds of delay between the scheduled DagRun start date and the actual DagRun start date",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag" },
       "metricName": "DAGScheduleDelay",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DAG Flie Processing Last Duration",
     "type": "timeseries",
     "description": "dag_processing.last_duration.{dag_filename}\nMilliseconds taken to load the given DAG file",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DAG Filename": "$dag_file" },
       "metricName": "DAGFileProcessingLastDuration",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DAG File Processing Last Run Seconds Ago",
     "type": "timeseries",
     "description": "dag_processing.last_run.seconds_ago.<dag_file>\nSeconds since <dag_file> was last processed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dimensions": { "DAG Filename": "$dag_file" },
       "metricName": "DAGFileProcessingLastRunSecondsAgo",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DAG Bag Size",
     "type": "timeseries",
     "description": "dagbag_size  \nNumber of DAGs found when the scheduler ran a scan based on it’s configuration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "DagBagSize",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Instance Started",
     "type": "timeseries",
     "description": "titi.start.<dagid>.<taskid>\nNumber of started task in a given dag. Similar to <job_name>_start but for task",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag", "Task": "$task" },
       "metricName": "TaskInstanceStarted",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Task Instance Finished",
     "type": "timeseries",
     "description": "ti.finish.<dagid>.<taskid>.<state>  \nNumber of completed task in a given dag. Similar to <job_name>_end but for task",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag", "Task": "$task" },
       "metricName": "TaskInstanceFinished",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Task Instance Queued Duration",
     "type": "timeseries",
     "description": "dag.{dag_id}.{task_id}.queued_duration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag", "Task": "$task" },
       "metricName": "TaskInstanceQueuedDuration",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Task Instance Duration",
     "type": "timeseries",
     "description": "dag.{dag_id}.{task_id}.duration  \nMilliseconds taken to load the given DAG file",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DAG": "$dag", "Task": "$task" },
       "metricName": "TaskInstanceDuration",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Running Slots",
     "type": "timeseries",
     "description": "pool.running_slots.{pool_name}  \nNumber of running slots in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "PoolRunningSlots",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Pool Open Slots",
     "type": "timeseries",
     "description": "pool.open_slots.{pool_name}  \nNumber of open slots in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "PoolOpenSlots",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Pool Queued Slots",
     "type": "timeseries",
     "description": "pool.queued_slots.{pool_name}  \nNumber of queued slots in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "PoolQueuedSlots",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Pool Deferred Slots",
     "type": "timeseries",
     "description": "pool.deferred_slots.{pool_name}  \nNumber of deferred slots in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "PoolDeferredSlots",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Pool Starving Tasks",
     "type": "timeseries",
     "description": "pool.starving_tasks.{pool_name}  \nNumber of starving tasks in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "PoolStarvingTasks",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import Errors",
     "type": "timeseries",
     "description": "dag_processing.import_errors\n \t\n\nNumber of errors from trying to parse DAG files",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "ImportErrors",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Job End",
     "type": "timeseries",
     "description": "<job_name>_end  \nNumber of ended <job_name> job, ex. SchedulerJob, LocalTaskJob",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "JobEnd",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "description": "dag_processing.processes  \nNumber of currently running DAG parsing processes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "Processes",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Orphaned",
     "type": "timeseries",
     "description": "dataset.orphaned  \n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "Orphaned",
       "namespace": "AmazonMWAA",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}